"use client";

import { useActionState, useState } from "react";
import { Activity, LoaderCircle, Pencil, Power, Save } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { initialFormState } from "@/modules/auth/types";
import { saveMaterialNorm, setMaterialNormActive } from "./actions";
import type { InventoryItem, InventoryServiceOption, ServiceMaterialNorm } from "./types";

function NormForm({ norm, services, items, onCancel }: { norm: ServiceMaterialNorm | null; services: InventoryServiceOption[]; items: InventoryItem[]; onCancel: () => void }) {
  const [state, action, pending] = useActionState(saveMaterialNorm, initialFormState);
  return <form action={action} className="space-y-4 rounded-2xl border bg-white p-5">{norm && <input type="hidden" name="normId" value={norm.id} />}<div className="flex items-center justify-between"><div><h2 className="font-semibold">{norm ? "Изменить норму" : "Новая норма"}</h2><p className="mt-1 text-xs text-[var(--muted)]">Количество материала на одну единицу процедуры.</p></div>{norm && <button type="button" onClick={onCancel} className="text-xs text-[var(--muted)]">Отмена</button>}</div><label className="block space-y-2"><span className="text-sm font-medium">Услуга *</span><select name="serviceId" defaultValue={norm?.serviceId ?? ""} required className="h-11 w-full rounded-xl border bg-white px-3.5 text-sm"><option value="" disabled>Выберите услугу</option>{services.filter((service) => service.isActive).map((service) => <option key={service.id} value={service.id}>{service.code} — {service.name}</option>)}</select></label><label className="block space-y-2"><span className="text-sm font-medium">Материал *</span><select name="itemId" defaultValue={norm?.itemId ?? ""} required className="h-11 w-full rounded-xl border bg-white px-3.5 text-sm"><option value="" disabled>Выберите материал</option>{items.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.sku} — {item.name} ({item.unit})</option>)}</select></label><label className="block space-y-2"><span className="text-sm font-medium">Количество *</span><Input name="quantity" type="number" min="0.001" step="0.001" defaultValue={norm?.quantity ?? 1} required /></label>{state.message && <p className={state.status === "success" ? "rounded-xl bg-emerald-50 px-3 py-2 text-xs text-emerald-800" : "rounded-xl bg-red-50 px-3 py-2 text-xs text-[var(--danger)]"}>{state.message}</p>}<Button className="w-full" disabled={pending}>{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Сохранить норму</Button></form>;
}

export function MaterialNormManager({ norms, services, items, canManage }: { norms: ServiceMaterialNorm[]; services: InventoryServiceOption[]; items: InventoryItem[]; canManage: boolean }) {
  const [editing, setEditing] = useState<ServiceMaterialNorm | null>(null);
  return <div className="grid gap-6 xl:grid-cols-[1fr_0.52fr]"><div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><div className="flex items-center gap-2"><Activity className="size-5 text-[var(--brand)]" /><h2 className="font-semibold">Нормы расхода</h2></div></div>{norms.length === 0 ? <p className="p-8 text-center text-sm text-[var(--muted)]">Нормы материалов ещё не настроены.</p> : <div className="divide-y">{norms.map((norm) => <div key={norm.id} className={norm.isActive ? "flex items-start gap-3 p-4" : "flex items-start gap-3 bg-[var(--surface-muted)] p-4 opacity-70"}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-[var(--surface-muted)] px-2 py-0.5 text-[10px] font-bold">{norm.serviceCode}</span><p className="font-semibold">{norm.serviceName}</p>{!norm.isActive && <span className="rounded-full bg-slate-200 px-2 py-0.5 text-[10px] font-semibold">Архив</span>}</div><p className="mt-2 text-sm">{norm.itemSku} — {norm.itemName}: <strong>{norm.quantity} {norm.unit}</strong></p></div>{canManage && <div className="flex gap-1"><button onClick={() => setEditing(norm)} className="grid size-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--surface-muted)]"><Pencil className="size-4" /></button><form action={setMaterialNormActive}><input type="hidden" name="normId" value={norm.id} /><input type="hidden" name="isActive" value={norm.isActive ? "false" : "true"} /><button className="grid size-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--surface-muted)]"><Power className="size-4" /></button></form></div>}</div>)}</div>}</div>{canManage && <NormForm key={editing?.id ?? "new"} norm={editing} services={services} items={items} onCancel={() => setEditing(null)} />}</div>;
}
