"use client";

import { useActionState, useState } from "react";
import { Building2, LoaderCircle, Pencil, Plus, Power, Save, Warehouse as WarehouseIcon } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { initialFormState } from "@/modules/auth/types";
import { saveWarehouse, setWarehouseActive } from "./actions";
import type { InventoryBranch, Warehouse } from "./types";

function WarehouseForm({ warehouse, branches, onCancel }: { warehouse: Warehouse | null; branches: InventoryBranch[]; onCancel: () => void }) {
  const [state, action, pending] = useActionState(saveWarehouse, initialFormState);
  return <form action={action} className="space-y-4 rounded-2xl border bg-white p-5">{warehouse && <input type="hidden" name="warehouseId" value={warehouse.id} />}<div className="flex items-center justify-between"><h2 className="font-semibold">{warehouse ? "Изменить склад" : "Новый склад"}</h2>{warehouse && <button type="button" onClick={onCancel} className="text-xs text-[var(--muted)]">Отмена</button>}</div><label className="block space-y-2"><span className="text-sm font-medium">Филиал *</span><select name="branchId" defaultValue={warehouse?.branchId ?? ""} required className="h-11 w-full rounded-xl border bg-white px-3.5 text-sm"><option value="" disabled>Выберите филиал</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label className="block space-y-2"><span className="text-sm font-medium">Название *</span><Input name="name" defaultValue={warehouse?.name ?? ""} minLength={2} maxLength={160} required placeholder="Основной склад" /></label>{state.message && <p className={state.status === "success" ? "rounded-xl bg-emerald-50 px-3 py-2 text-xs text-emerald-800" : "rounded-xl bg-red-50 px-3 py-2 text-xs text-[var(--danger)]"}>{state.message}</p>}<Button className="w-full" disabled={pending}>{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Сохранить склад</Button></form>;
}

export function WarehouseManager({ warehouses, branches, canManage }: { warehouses: Warehouse[]; branches: InventoryBranch[]; canManage: boolean }) {
  const [editing, setEditing] = useState<Warehouse | null>(null);
  return <div className="grid gap-6 xl:grid-cols-[1fr_0.6fr]"><div className="grid gap-4 md:grid-cols-2">{warehouses.map((warehouse) => <div key={warehouse.id} className={warehouse.isActive ? "rounded-2xl border bg-white p-5" : "rounded-2xl border bg-[var(--surface-muted)] p-5 opacity-70"}><div className="flex items-start gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[var(--brand-soft)] text-[var(--brand)]"><WarehouseIcon className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="font-semibold">{warehouse.name}</h2>{!warehouse.isActive && <span className="rounded-full bg-slate-200 px-2 py-0.5 text-[10px] font-semibold">Архив</span>}</div><p className="mt-1 flex items-center gap-1.5 text-xs text-[var(--muted)]"><Building2 className="size-3.5" />{warehouse.branchName}</p></div>{canManage && <div className="flex gap-1"><button onClick={() => setEditing(warehouse)} className="grid size-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--surface-muted)]"><Pencil className="size-4" /></button><form action={setWarehouseActive}><input type="hidden" name="warehouseId" value={warehouse.id} /><input type="hidden" name="isActive" value={warehouse.isActive ? "false" : "true"} /><button className="grid size-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--surface-muted)]"><Power className="size-4" /></button></form></div>}</div></div>)}{warehouses.length === 0 && <div className="rounded-2xl border bg-white p-8 text-center text-sm text-[var(--muted)] md:col-span-2">Склады ещё не созданы.</div>}</div>{canManage ? <WarehouseForm key={editing?.id ?? "new"} warehouse={editing} branches={branches} onCancel={() => setEditing(null)} /> : <div className="rounded-2xl bg-[var(--surface-muted)] p-5 text-sm text-[var(--muted)]"><Plus className="mb-3 size-5" />Для изменения складов требуется право управления.</div>}</div>;
}
