"use client";

import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Named {id:string;name:string;organizationId?:string;branchIds?:string[];firstName?:string;lastName?:string}
interface Task {id:string;organizationId:string;branchId:string|null;branchName?:string;assignedEmployeeId:string|null;assignedEmployeeName?:string;title:string;description:string|null;priority:"low"|"normal"|"high"|"urgent";status:"open"|"in_progress"|"completed"|"cancelled";dueAt:string|null;createdAt:string;comments?:Comment[]}
interface Comment {id:string;body:string;createdAt:string}

const columns=[{key:"open",label:"Новые"},{key:"in_progress",label:"В работе"},{key:"completed",label:"Завершены"},{key:"cancelled",label:"Отменены"}] as const;
const priorityLabels={low:"Низкий",normal:"Обычный",high:"Высокий",urgent:"Срочный"};

export default function TasksPage(){const {session,request}=useAuth();const [tasks,setTasks]=useState<Task[]>([]);const [organizations,setOrganizations]=useState<Named[]>([]);const [branches,setBranches]=useState<Named[]>([]);const [employees,setEmployees]=useState<Named[]>([]);
  const [selected,setSelected]=useState<Task|null>(null);const [showCreate,setShowCreate]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");const canManage=session.permissions.includes("tasks.manage");
  const load=useCallback(async()=>{setLoading(true);try{const [nextTasks,nextOrganizations,nextBranches,nextEmployees]=await Promise.all([request<Task[]>("/tasks"),request<Named[]>("/organizations"),request<Named[]>("/branches"),request<Named[]>("/employees")]);setTasks(nextTasks);setOrganizations(nextOrganizations);setBranches(nextBranches);setEmployees(nextEmployees);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[request]);
  useEffect(()=>{void load();},[load]);
  const overdue=useMemo(()=>tasks.filter(task=>task.dueAt&&new Date(task.dueAt)<new Date()&&!['completed','cancelled'].includes(task.status)).length,[tasks]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element),due=String(form.get("dueAt")||"");setSaving(true);
    try{await request("/tasks",{method:"POST",body:JSON.stringify({organizationId:form.get("organizationId"),branchId:value(form,"branchId"),assignedEmployeeId:value(form,"assignedEmployeeId"),title:form.get("title"),description:value(form,"description"),priority:form.get("priority"),dueAt:due?new Date(due).toISOString():undefined})});element.reset();setShowCreate(false);await load();setNotice("Задача создана");}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  async function transition(task:Task,status:Task["status"]){try{await request(`/tasks/${task.id}/transition`,{method:"POST",body:JSON.stringify({status})});await load();if(selected?.id===task.id)setSelected(await request<Task>(`/tasks/${task.id}`));}catch(error){setNotice(message(error));}}
  async function open(task:Task){try{setSelected(await request<Task>(`/tasks/${task.id}`));}catch(error){setNotice(message(error));}}
  async function comment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const element=event.currentTarget,form=new FormData(element);try{await request(`/tasks/${selected.id}/comments`,{method:"POST",body:JSON.stringify({body:form.get("body")})});element.reset();setSelected(await request<Task>(`/tasks/${selected.id}`));}catch(error){setNotice(message(error));}}
  return <main className="data-page"><div className="page-heading"><div><span className="eyebrow">Командная работа</span><h1>Задачи</h1><p>Поручения, сроки и контроль работы сотрудников.</p></div>{canManage&&<button className="primary" onClick={()=>setShowCreate(true)}>＋ Новая задача</button>}</div>
    {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <section className="work-metrics"><Metric value={tasks.filter(item=>item.status==="open").length} label="Новых"/><Metric value={tasks.filter(item=>item.status==="in_progress").length} label="В работе"/><Metric value={overdue} label="Просрочено" danger={overdue>0}/><Metric value={tasks.filter(item=>item.status==="completed").length} label="Завершено"/></section>
    {loading?<div className="data-empty">Загружаем задачи…</div>:<section className="task-board">{columns.map(column=><div className="task-column" key={column.key}><header><b>{column.label}</b><span>{tasks.filter(task=>task.status===column.key).length}</span></header><div>{tasks.filter(task=>task.status===column.key).map(task=><article className="task-card" key={task.id} onClick={()=>void open(task)}><div><span className={`priority ${task.priority}`}>{priorityLabels[task.priority]}</span>{task.dueAt&&<time className={isOverdue(task)?"overdue":""}>{formatDue(task.dueAt)}</time>}</div><h3>{task.title}</h3>{task.description&&<p>{task.description}</p>}<footer><span>{task.assignedEmployeeName||"Не назначена"}</span>{task.branchName&&<small>{task.branchName}</small>}</footer></article>)}{tasks.every(task=>task.status!==column.key)&&<div className="column-empty">Нет задач</div>}</div></div>)}</section>}
    {showCreate&&<div className="modal-backdrop" onMouseDown={()=>setShowCreate(false)}><form className="patient-form-modal task-form" onSubmit={create} onMouseDown={event=>event.stopPropagation()}><ModalTitle title="Новая задача" close={()=>setShowCreate(false)}/><div className="patient-form-grid"><label className="wide">Название<input name="title" required autoFocus/></label><label>Организация<select name="organizationId" required defaultValue=""><option value="" disabled>Выберите</option>{organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Филиал <small>необязательно</small><select name="branchId" defaultValue=""><option value="">Вся организация</option>{branches.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Исполнитель <small>необязательно</small><select name="assignedEmployeeId" defaultValue=""><option value="">Не назначен</option>{employees.map(item=><option key={item.id} value={item.id}>{employeeName(item)}</option>)}</select></label><label>Приоритет<select name="priority" defaultValue="normal"><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="urgent">Срочный</option></select></label><label>Срок <small>необязательно</small><input name="dueAt" type="datetime-local"/></label><label className="wide">Описание <small>необязательно</small><textarea name="description" rows={4}/></label></div><ModalActions saving={saving} close={()=>setShowCreate(false)} label="Создать задачу"/></form></div>}
    {selected&&<div className="modal-backdrop side" onMouseDown={()=>setSelected(null)}><aside className="task-drawer" onMouseDown={event=>event.stopPropagation()}><ModalTitle title={selected.title} close={()=>setSelected(null)}/><div className="task-detail-meta"><span className={`priority ${selected.priority}`}>{priorityLabels[selected.priority]}</span><span>{statusLabel(selected.status)}</span>{selected.dueAt&&<time className={isOverdue(selected)?"overdue":""}>{formatDue(selected.dueAt)}</time>}</div><p className="task-description">{selected.description||"Описание не добавлено."}</p><dl><Info label="Исполнитель" value={selected.assignedEmployeeName||"Не назначен"}/><Info label="Филиал" value={selected.branchName||"Вся организация"}/><Info label="Создана" value={formatDate(selected.createdAt)}/></dl>{canManage&&!['completed','cancelled'].includes(selected.status)&&<div className="task-actions">{selected.status==="open"&&<button className="secondary" onClick={()=>void transition(selected,"in_progress")}>Взять в работу</button>}<button className="primary" onClick={()=>void transition(selected,"completed")}>Завершить</button></div>}<section className="task-comments"><h3>Комментарии</h3>{selected.comments?.map(item=><article key={item.id}><p>{item.body}</p><time>{formatDate(item.createdAt)}</time></article>)}{canManage&&<form onSubmit={comment}><textarea name="body" required placeholder="Добавить комментарий" rows={3}/><button className="secondary">Отправить</button></form>}</section></aside></div>}
  </main>}

function Metric({value,label,danger=false}:{value:number;label:string;danger?:boolean}){return <div className={danger?"danger":""}><b>{value}</b><span>{label}</span></div>}
function ModalTitle({title,close}:{title:string;close:()=>void}){return <div className="modal-heading"><div><span className="eyebrow">Рабочий процесс</span><h2>{title}</h2></div><button type="button" onClick={close}>×</button></div>}
function ModalActions({saving,close,label}:{saving:boolean;close:()=>void;label:string}){return <div className="modal-actions"><button type="button" className="secondary" onClick={close}>Отмена</button><button className="primary" disabled={saving}>{saving?"Сохраняем…":label}</button></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function value(form:FormData,name:string){return String(form.get(name)||"").trim()||undefined}
function employeeName(item:Named){return `${item.lastName??""} ${item.firstName??""}`.trim()||item.name}
function isOverdue(task:Task){return Boolean(task.dueAt&&new Date(task.dueAt)<new Date()&&!['completed','cancelled'].includes(task.status))}
function formatDue(value:string){return new Date(value).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function formatDate(value:string){return new Date(value).toLocaleString("ru-RU",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function statusLabel(value:Task["status"]){return ({open:"Новая",in_progress:"В работе",completed:"Завершена",cancelled:"Отменена"})[value]}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос"}
