"use client";

import { useCallback,useEffect,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Named {id:string;name:string;organizationId?:string}
interface Acceptance {summary:{presentedItems:number;acceptedItems:number;presentedAmountMinor:number;acceptedAmountMinor:number;itemAcceptanceRateBps:number|null;amountAcceptanceRateBps:number|null};byService:{serviceId:string;serviceName:string;presentedItems:number;acceptedItems:number;presentedAmountMinor:number;acceptedAmountMinor:number;itemAcceptanceRateBps:number|null}[]}
interface Chairs {chairs:{chairId:string;chairName:string;branchName:string;appointmentCount:number;completedCount:number;noShowCount:number;bookedMinutes:number;revenueMinor:number;completionRateBps:number|null;revenuePerCompletedHourMinor:number|null}[]}
interface Margin {summary:{revenueMinor:number;variableCostMinor:number;contributionMarginMinor:number;contributionMarginBps:number|null};byService:unknown[]}
interface Marketing {bySource:{sourceId:string|null;sourceName:string;leadCount:number;conversionCount:number;revenueMinor:number;conversionRateBps:number|null}[]}
interface Inventory {products:{productId:string;sku:string;name:string;unit:string;onHandQuantity:number;minimumStock:number;stockValueMinor:number;consumedQuantity:number;consumptionCostMinor:number;writeoffCostMinor:number;daysOfStock:number|null;belowMinimum:boolean}[]}

function defaultRange(){const to=new Date(),from=new Date();from.setDate(to.getDate()-29);return{from:localDate(from),to:localDate(to)}}

export default function AnalyticsPage(){const {session,request}=useAuth();const initial=defaultRange();const [organizations,setOrganizations]=useState<Named[]>([]);const [branches,setBranches]=useState<Named[]>([]);const [organizationId,setOrganizationId]=useState("");const [branchId,setBranchId]=useState("");const [from,setFrom]=useState(initial.from);const [to,setTo]=useState(initial.to);const [acceptance,setAcceptance]=useState<Acceptance|null>(null);const [chairs,setChairs]=useState<Chairs|null>(null);const [margin,setMargin]=useState<Margin|null>(null);const [marketing,setMarketing]=useState<Marketing|null>(null);const [inventory,setInventory]=useState<Inventory|null>(null);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const canFinancial=session.permissions.includes("analytics.financial.read");
  const loadCatalog=useCallback(async()=>{try{const [orgs,nextBranches]=await Promise.all([request<Named[]>("/organizations"),request<Named[]>("/branches")]);setOrganizations(orgs);setBranches(nextBranches);setOrganizationId(current=>current||orgs[0]?.id||"");}catch(error){setNotice(message(error));setLoading(false);}},[request]);useEffect(()=>{void loadCatalog();},[loadCatalog]);
  const load=useCallback(async()=>{if(!organizationId)return;setLoading(true);setNotice("");const params=new URLSearchParams({organizationId,from,to,currency:"KZT"});if(branchId)params.set("branchId",branchId);try{const basic=await Promise.all([request<Acceptance>(`/analytics/treatment-acceptance?${params}`),request<Inventory>(`/analytics/inventory?${params}`)]);setAcceptance(basic[0]);setInventory(basic[1]);if(canFinancial){const financial=await Promise.all([request<Chairs>(`/analytics/chair-economics?${params}`),request<Margin>(`/analytics/contribution-margin?${params}`),request<Marketing>(`/analytics/marketing-attribution?${params}`)]);setChairs(financial[0]);setMargin(financial[1]);setMarketing(financial[2]);}}catch(error){setNotice(message(error));}finally{setLoading(false);}},[branchId,canFinancial,from,organizationId,request,to]);
  useEffect(()=>{if(organizationId)void load();},[load,organizationId]);
  function apply(event:FormEvent){event.preventDefault();void load()}
  const filteredBranches=branches.filter(item=>!item.organizationId||item.organizationId===organizationId),maxChair=Math.max(1,...(chairs?.chairs.map(item=>item.revenueMinor)??[1]));
  return <main className="data-page"><div className="page-heading"><div><span className="eyebrow">Показатели клиники</span><h1>Аналитика</h1><p>Лечение, загрузка кресел, экономика и движение материалов.</p></div></div>
    {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <form className="analytics-filters" onSubmit={apply}><label>Организация<select value={organizationId} onChange={event=>{setOrganizationId(event.target.value);setBranchId("")}} required><option value="" disabled>Выберите</option>{organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Филиал<select value={branchId} onChange={event=>setBranchId(event.target.value)}><option value="">Все филиалы</option>{filteredBranches.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>С<input type="date" value={from} onChange={event=>setFrom(event.target.value)} required/></label><label>По<input type="date" value={to} onChange={event=>setTo(event.target.value)} required/></label><button className="primary" disabled={loading}>{loading?"Считаем…":"Обновить"}</button></form>
    <section className="analytics-kpis"><Kpi label="Принятие планов" value={percent(acceptance?.summary.itemAcceptanceRateBps)} note={`${acceptance?.summary.acceptedItems??0} из ${acceptance?.summary.presentedItems??0} позиций`}/><Kpi label="Принято на сумму" value={money(acceptance?.summary.acceptedAmountMinor??0)} note="KZT, за выбранный период"/><Kpi label="Выручка" value={canFinancial?money(margin?.summary.revenueMinor??0):"Нет доступа"} note={canFinancial?"По начисленным услугам":"Требуется analytics.financial.read"}/><Kpi label="Маржинальность" value={canFinancial?percent(margin?.summary.contributionMarginBps):"—"} note={canFinancial?money(margin?.summary.contributionMarginMinor??0):"Финансовые данные скрыты"}/></section>
    <div className="analytics-grid"><section className="analytics-card"><div className="panel-heading"><div><span className="eyebrow">Клиническая эффективность</span><h2>Принятие по услугам</h2></div></div>{acceptance?.byService.length?<div className="analytics-list">{acceptance.byService.slice(0,8).map(item=><article key={item.serviceId}><span><b>{item.serviceName}</b><small>{item.acceptedItems} из {item.presentedItems}</small></span><div><i style={{width:`${Math.max(2,(item.itemAcceptanceRateBps??0)/100)}%`}}/></div><strong>{percent(item.itemAcceptanceRateBps)}</strong></article>)}</div>:<Empty/>}</section>
      <section className="analytics-card"><div className="panel-heading"><div><span className="eyebrow">Загрузка</span><h2>Экономика кресел</h2></div></div>{!canFinancial?<Locked/>:chairs?.chairs.length?<div className="analytics-bars">{chairs.chairs.slice(0,8).map(item=><article key={item.chairId}><span><b>{item.chairName}</b><small>{item.branchName} · {item.completedCount} приёмов</small></span><div><i style={{width:`${Math.max(2,item.revenueMinor*100/maxChair)}%`}}/></div><strong>{money(item.revenueMinor)}</strong></article>)}</div>:<Empty/>}</section>
      <section className="analytics-card"><div className="panel-heading"><div><span className="eyebrow">Маркетинг</span><h2>Источники пациентов</h2></div></div>{!canFinancial?<Locked/>:marketing?.bySource.length?<div className="source-table">{marketing.bySource.slice(0,8).map((item,index)=><article key={item.sourceId??index}><i>{index+1}</i><span><b>{item.sourceName}</b><small>{item.leadCount} лидов · {item.conversionCount} конверсий</small></span><strong>{percent(item.conversionRateBps)}</strong><b>{money(item.revenueMinor)}</b></article>)}</div>:<Empty/>}</section>
      <section className="analytics-card"><div className="panel-heading"><div><span className="eyebrow">Материалы</span><h2>Запасы и расход</h2></div></div>{inventory?.products.length?<div className="inventory-analytics">{inventory.products.slice(0,8).map(item=><article key={item.productId}><span><b>{item.name}</b><small>{item.sku} · расход {quantity(item.consumedQuantity)} {item.unit}</small></span><strong className={item.belowMinimum?"low":""}>{quantity(item.onHandQuantity)} {item.unit}</strong><small>{item.daysOfStock===null?"Нет расхода":`${item.daysOfStock} дн.`}</small></article>)}</div>:<Empty/>}</section></div>
  </main>}

function Kpi({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><b>{value}</b><small>{note}</small></article>}
function Empty(){return <div className="inline-empty">За выбранный период данных нет.</div>}
function Locked(){return <div className="inline-empty">Нет доступа к финансовой аналитике.</div>}
function localDate(date:Date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60_000).toISOString().slice(0,10)}
function percent(value:number|null|undefined){return value==null?"—":`${(value/100).toLocaleString("ru-RU",{maximumFractionDigits:1})}%`}
function money(value:number){return new Intl.NumberFormat("ru-RU",{style:"currency",currency:"KZT",maximumFractionDigits:0}).format(value/100)}
function quantity(value:number){return new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(value)}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось загрузить показатели"}
