"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type CSSProperties, type DragEvent, type FormEvent, type PointerEvent } from "react";
import { useAuth } from "./auth-shell";

interface Patient { id:string; firstName:string; lastName:string; middleName?:string; phone:string; birthDate?:string; notes?:string; }
interface Employee { firstName:string; lastName:string; doctorId?:string; }
interface Chair { id:string; name:string; branchId:string; }
interface Branch { id:string; name:string; }
interface Appointment { id:string; patientId?:string; doctorId?:string; branchId?:string; chairId?:string; startsAt:string; endsAt:string; status:string; patientName:string; doctorName:string; chairName?:string; reason?:string; notes?:string; }
interface Balance { balances:{currency:string;balanceMinor:number}[] }
type ViewMode="day"|"week";type GroupMode="doctor"|"chair";

const START_HOUR=8,END_HOUR=20,HOUR_HEIGHT=56;
const statusLabels:Record<string,string>={created:"Создана",awaiting_confirmation:"Ждёт подтверждения",confirmed:"Подтверждена",checked_in:"Пациент пришёл",in_progress:"В кресле",completed:"Завершена",cancelled:"Отменена",no_show:"Не пришёл",rescheduled:"Перенесена"};
const nextAction:Record<string,[string,string]|undefined>={created:["confirm","Подтвердить"],awaiting_confirmation:["confirm","Подтвердить"],confirmed:["check-in","Пациент пришёл"],checked_in:["start","Начать приём"],in_progress:["complete","Завершить"]};

export function ClinicDashboard(){
  const {session,request}=useAuth();
  const [patients,setPatients]=useState<Patient[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[chairs,setChairs]=useState<Chair[]>([]),[branches,setBranches]=useState<Branch[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]);
  const [anchor,setAnchor]=useState(()=>startOfDay(new Date())),[view,setView]=useState<ViewMode>("day"),[group,setGroup]=useState<GroupMode>("doctor");
  const [doctorFilter,setDoctorFilter]=useState(""),[branchFilter,setBranchFilter]=useState(""),[query,setQuery]=useState("");
  const [selected,setSelected]=useState<Appointment|null>(null),[selectedPatient,setSelectedPatient]=useState<Patient|null>(null),[selectedBalance,setSelectedBalance]=useState<Balance|null>(null);
  const [showCreate,setShowCreate]=useState(false),[showQuickPatient,setShowQuickPatient]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
  const doctors=useMemo(()=>employees.filter(item=>item.doctorId),[employees]);const range=useMemo(()=>calendarRange(anchor,view),[anchor,view]);
  const load=useCallback(async()=>{setLoading(true);try{const [p,e,c,b,a]=await Promise.all([request<Patient[]>("/patients"),request<Employee[]>("/employees"),request<Chair[]>("/chairs"),request<Branch[]>("/branches").catch(()=>[]),request<Appointment[]>(`/appointments?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`)]);setPatients(p);setEmployees(e);setChairs(c);setBranches(b);setAppointments(a);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[range,request]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!selected?.patientId){setSelectedPatient(null);setSelectedBalance(null);return;}setSelectedPatient(null);void request<Patient>(`/patients/${selected.patientId}`).then(setSelectedPatient).catch(()=>{});if(session.permissions.includes("finance.read"))void request<Balance>(`/patients/${selected.patientId}/balance`).then(setSelectedBalance).catch(()=>{});},[request,selected,session.permissions]);

  const visibleAppointments=useMemo(()=>appointments.filter(item=>(!doctorFilter||item.doctorId===doctorFilter)&&(!branchFilter||item.branchId===branchFilter)&&(!query||`${item.patientName} ${item.doctorName} ${item.reason??""}`.toLocaleLowerCase("ru-RU").includes(query.toLocaleLowerCase("ru-RU")))),[appointments,branchFilter,doctorFilter,query]);
  const columns=useMemo(()=>view==="week"?weekDays(anchor).map(date=>({id:dateKey(date),label:date.toLocaleDateString("ru-RU",{weekday:"short",day:"2-digit",month:"short"}),date})):group==="doctor"?doctors.filter(item=>!doctorFilter||item.doctorId===doctorFilter).map(item=>({id:item.doctorId!,label:`${item.lastName} ${item.firstName}`,meta:"Врач"})):chairs.filter(item=>!branchFilter||item.branchId===branchFilter).map(item=>({id:item.id,label:item.name,meta:branches.find(branch=>branch.id===item.branchId)?.name??"Кабинет"})),[anchor,branchFilter,branches,chairs,doctorFilter,doctors,group,view]);

  async function createAppointment(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const doctor=doctors.find(item=>item.doctorId===form.get("doctorId"));const chair=chairs.find(item=>item.id===form.get("chairId"));if(!doctor||!chair)return setNotice("Выберите врача и кабинет");const starts=new Date(String(form.get("startsAt"))),ends=new Date(starts.getTime()+Number(form.get("duration"))*60_000);try{await request("/appointments",{method:"POST",body:JSON.stringify({patientId:form.get("patientId"),doctorId:doctor.doctorId,branchId:chair.branchId,chairId:chair.id,startsAt:starts.toISOString(),endsAt:ends.toISOString(),reason:form.get("reason"),source:"internal",serviceIds:[]})});element.reset();setShowCreate(false);await load();setNotice("Запись создана");}catch(error){setNotice(message(error));}}
  async function createPatient(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element);try{await request("/patients",{method:"POST",body:JSON.stringify({lastName:form.get("lastName"),firstName:form.get("firstName"),phone:form.get("phone"),sex:"unknown"})});element.reset();setShowQuickPatient(false);await load();setNotice("Пациент добавлен — теперь его можно выбрать в записи");}catch(error){setNotice(message(error));}}
  async function transition(appointment:Appointment,action:string){try{const body=action==="cancel"?JSON.stringify({reason:window.prompt("Причина отмены")||"Отменено администратором"}):"{}";await request(`/appointments/${appointment.id}/${action}`,{method:"POST",body});await load();setSelected(null);setNotice("Статус записи обновлён");}catch(error){setNotice(message(error));}}
  async function reschedule(appointment:Appointment,startsAt:Date,endsAt:Date,chairId=appointment.chairId){try{await request(`/appointments/${appointment.id}/reschedule`,{method:"POST",body:JSON.stringify({startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),chairId:chairId||null,reason:"Перенесено в расписании"})});await load();setSelected(null);setNotice("Запись перенесена");}catch(error){setNotice(message(error));await load();}}
  function drop(event:DragEvent<HTMLDivElement>,columnId:string){event.preventDefault();const id=event.dataTransfer.getData("text/appointment-id"),appointment=appointments.find(item=>item.id===id);if(!appointment)return;const rect=event.currentTarget.getBoundingClientRect(),minutes=Math.max(0,Math.min((END_HOUR-START_HOUR)*60-15,Math.round(((event.clientY-rect.top)/HOUR_HEIGHT*60)/15)*15));const base=view==="week"?new Date(`${columnId}T00:00:00`):new Date(anchor);base.setHours(START_HOUR+Math.floor(minutes/60),minutes%60,0,0);const duration=new Date(appointment.endsAt).getTime()-new Date(appointment.startsAt).getTime();void reschedule(appointment,base,new Date(base.getTime()+duration),view==="day"&&group==="chair"?columnId:appointment.chairId);}
  function resizeStart(event:PointerEvent<HTMLButtonElement>,appointment:Appointment){event.preventDefault();event.stopPropagation();const origin=event.clientY,originalEnd=new Date(appointment.endsAt),start=new Date(appointment.startsAt),originalDuration=originalEnd.getTime()-start.getTime();let nextDuration=originalDuration;const move=(pointer:globalThis.PointerEvent)=>{nextDuration=Math.max(15*60_000,Math.round((originalDuration+(pointer.clientY-origin)/HOUR_HEIGHT*60*60_000)/(15*60_000))*15*60_000);setAppointments(items=>items.map(item=>item.id===appointment.id?{...item,endsAt:new Date(start.getTime()+nextDuration).toISOString()}:item));};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);void reschedule(appointment,start,new Date(start.getTime()+nextDuration));};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);}
  function shiftDate(delta:number){const next=new Date(anchor);next.setDate(next.getDate()+delta*(view==="week"?7:1));setAnchor(next);}

  return <main className="schedule-page">
    <header className="schedule-header"><div><span className="page-kicker">Календарь клиники</span><h1>Расписание</h1></div><div className="schedule-header-actions"><button className="secondary" onClick={()=>setAnchor(startOfDay(new Date()))}>Сегодня</button><button className="primary" onClick={()=>setShowCreate(true)}>＋ Новая запись</button></div></header>
    {notice&&<div className="toast-notice" role="status"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
    <section className="schedule-toolbar"><div className="date-control"><button onClick={()=>shiftDate(-1)}>‹</button><button onClick={()=>shiftDate(1)}>›</button><b>{rangeLabel(anchor,view)}</b></div><div className="segmented"><button className={view==="day"?"active":""} onClick={()=>setView("day")}>День</button><button className={view==="week"?"active":""} onClick={()=>setView("week")}>Неделя</button></div><div className="toolbar-divider"/><label className="toolbar-search">⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Найти пациента"/></label><select value={branchFilter} onChange={event=>setBranchFilter(event.target.value)}><option value="">Все филиалы</option>{branches.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={doctorFilter} onChange={event=>setDoctorFilter(event.target.value)}><option value="">Все врачи</option>{doctors.map(item=><option value={item.doctorId} key={item.doctorId}>{item.lastName} {item.firstName}</option>)}</select>{view==="day"&&<div className="segmented"><button className={group==="doctor"?"active":""} onClick={()=>setGroup("doctor")}>Врачи</button><button className={group==="chair"?"active":""} onClick={()=>setGroup("chair")}>Кабинеты</button></div>}</section>
    <section className="scheduler-shell"><div className="scheduler-corner">GMT+5</div><div className="scheduler-columns-head" style={{"--columns":Math.max(columns.length,1)} as CSSProperties}>{columns.map(column=><div key={column.id}><span>{column.label}</span>{"meta" in column&&<small>{column.meta}</small>}<i>{visibleAppointments.filter(item=>belongs(item,column.id,view,group)).length}</i></div>)}</div><div className="time-rail">{Array.from({length:END_HOUR-START_HOUR+1},(_,index)=><time key={index}>{String(START_HOUR+index).padStart(2,"0")}:00</time>)}</div>
      <div className="scheduler-grid" style={{"--columns":Math.max(columns.length,1),"--hours":END_HOUR-START_HOUR} as CSSProperties}>{loading?<div className="scheduler-loading">Загружаем расписание…</div>:columns.length===0?<div className="scheduler-loading">Добавьте врачей или кабинеты, чтобы построить расписание.</div>:columns.map(column=><div className="schedule-column" key={column.id} onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,column.id)}>{visibleAppointments.filter(item=>belongs(item,column.id,view,group)).map(item=><AppointmentCard key={item.id} appointment={item} onSelect={()=>setSelected(item)} onResize={event=>resizeStart(event,item)}/>)}</div>)}</div>
    </section><div className="schedule-legend"><span><i data-status="confirmed"/>Подтверждена</span><span><i data-status="checked_in"/>Пациент пришёл</span><span><i data-status="in_progress"/>В кресле</span><span><i data-status="created"/>Ожидает</span><small>Перетащите запись, чтобы перенести · потяните нижнюю границу, чтобы изменить длительность</small></div>
    {showCreate&&<AppointmentCreateDrawer patients={patients} doctors={doctors} chairs={chairs} defaultDate={anchor} showPatient={showQuickPatient} onShowPatient={setShowQuickPatient} onPatient={createPatient} onSubmit={createAppointment} onClose={()=>{setShowCreate(false);setShowQuickPatient(false);}}/>}
    {selected&&<AppointmentDrawer appointment={selected} patient={selectedPatient} balance={selectedBalance} onClose={()=>setSelected(null)} onTransition={transition} onReschedule={reschedule}/>}
  </main>;
}

function AppointmentCard({appointment,onSelect,onResize}:{appointment:Appointment;onSelect:()=>void;onResize:(event:PointerEvent<HTMLButtonElement>)=>void}){const start=new Date(appointment.startsAt),end=new Date(appointment.endsAt),top=((start.getHours()+start.getMinutes()/60)-START_HOUR)*HOUR_HEIGHT,height=Math.max(30,(end.getTime()-start.getTime())/3_600_000*HOUR_HEIGHT);return <article className="calendar-appointment" data-status={appointment.status} draggable onDragStart={event=>event.dataTransfer.setData("text/appointment-id",appointment.id)} onClick={onSelect} style={{top,height}}><span className="appointment-stripe"/><div><time>{time(start)}–{time(end)}</time><b>{appointment.patientName}</b><small>{appointment.reason||"Приём"}</small><em>{appointment.doctorName} · {appointment.chairName||"Кабинет не указан"}</em></div><i className="state-dot"/><button className="resize-handle" aria-label="Изменить длительность" onPointerDown={onResize}/></article>}

function AppointmentCreateDrawer({patients,doctors,chairs,defaultDate,showPatient,onShowPatient,onPatient,onSubmit,onClose}:{patients:Patient[];doctors:Employee[];chairs:Chair[];defaultDate:Date;showPatient:boolean;onShowPatient:(value:boolean)=>void;onPatient:(event:FormEvent<HTMLFormElement>)=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;onClose:()=>void}){return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="context-drawer create-drawer" onMouseDown={event=>event.stopPropagation()}><header><div><span className="page-kicker">Расписание</span><h2>Новая запись</h2></div><button onClick={onClose}>×</button></header>{showPatient?<form className="drawer-form" onSubmit={onPatient}><div className="drawer-section-title"><b>Быстрый пациент</b><button type="button" onClick={()=>onShowPatient(false)}>← К записи</button></div><label>Фамилия<input name="lastName" required autoFocus/></label><label>Имя<input name="firstName" required/></label><label>Телефон<input name="phone" type="tel" required/></label><button className="primary">Добавить пациента</button></form>:<form className="drawer-form" onSubmit={onSubmit}><label>Пациент<div className="field-with-action"><select name="patientId" required defaultValue=""><option value="" disabled>Выберите пациента</option>{patients.map(item=><option value={item.id} key={item.id}>{item.lastName} {item.firstName}</option>)}</select><button type="button" onClick={()=>onShowPatient(true)}>＋</button></div></label><label>Врач<select name="doctorId" required defaultValue=""><option value="" disabled>Выберите врача</option>{doctors.map(item=><option value={item.doctorId} key={item.doctorId}>{item.lastName} {item.firstName}</option>)}</select></label><div className="form-row"><label>Дата и время<input name="startsAt" type="datetime-local" defaultValue={localInput(defaultDate)} required/></label><label>Минут<input name="duration" type="number" min="15" step="15" max="720" defaultValue="30" required/></label></div><label>Кабинет<select name="chairId" required defaultValue=""><option value="" disabled>Выберите кабинет</option>{chairs.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Причина визита<input name="reason" placeholder="Консультация, лечение…"/></label><footer><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary">Создать запись</button></footer></form>}</aside></div>}

function AppointmentDrawer({appointment,patient,balance,onClose,onTransition,onReschedule}:{appointment:Appointment;patient:Patient|null;balance:Balance|null;onClose:()=>void;onTransition:(appointment:Appointment,action:string)=>Promise<void>;onReschedule:(appointment:Appointment,start:Date,end:Date)=>Promise<void>}){const action=nextAction[appointment.status],start=new Date(appointment.startsAt),end=new Date(appointment.endsAt);function move(){const value=window.prompt("Новая дата и время (ГГГГ-ММ-ДД ЧЧ:ММ)",`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,"0")}-${String(start.getDate()).padStart(2,"0")} ${time(start)}`);if(!value)return;const next=new Date(value.replace(" ","T"));if(Number.isNaN(next.getTime()))return;void onReschedule(appointment,next,new Date(next.getTime()+(end.getTime()-start.getTime())));}return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="context-drawer appointment-drawer" onMouseDown={event=>event.stopPropagation()}><header><div><StatusBadge status={appointment.status}/><h2>{appointment.patientName}</h2><p>{appointment.reason||"Стоматологический приём"}</p></div><button onClick={onClose}>×</button></header><div className="patient-callout"><span>{initials(appointment.patientName)}</span><div><b>{patient?`${patient.lastName} ${patient.firstName}`:appointment.patientName}</b><small>{patient?.birthDate?`${age(patient.birthDate)} лет · `:""}{patient?.phone||"Телефон загружается…"}</small></div></div><section><h3>Запись</h3><dl><Info label="Дата" value={start.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}/><Info label="Время" value={`${time(start)}–${time(end)} · ${Math.round((end.getTime()-start.getTime())/60000)} мин`}/><Info label="Врач" value={appointment.doctorName}/><Info label="Кабинет" value={appointment.chairName||"Не указан"}/><Info label="ИИН" value="Не указан"/></dl></section><section><h3>Контекст пациента</h3><div className="clinical-alert"><i>!</i><span><b>Медицинские предупреждения</b><small>{patient?.notes||"Активных предупреждений нет"}</small></span></div><dl><Info label="Баланс" value={balance?.balances.length?balance.balances.map(item=>money(item.balanceMinor,item.currency)).join(" · "):"0 ₸"}/><Info label="Последний визит" value="Нет данных"/><Info label="Следующий визит" value="Эта запись"/></dl></section><div className="drawer-primary-actions">{action&&<button className="primary" onClick={()=>void onTransition(appointment,action[0])}>{action[1]}</button>}{appointment.status==="confirmed"&&<button className="secondary" onClick={()=>void onTransition(appointment,"no-show")}>Не пришёл</button>}</div><div className="drawer-secondary-actions"><button onClick={move}>Перенести</button><button className="danger-link" onClick={()=>void onTransition(appointment,"cancel")}>Отменить</button>{appointment.patientId&&<Link href={`/patients/${appointment.patientId}`}>Открыть пациента →</Link>}</div></aside></div>}

function StatusBadge({status}:{status:string}){return <span className="status-badge" data-status={status}><i/>{statusLabels[status]??status}</span>}
function Info({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function belongs(item:Appointment,columnId:string,view:ViewMode,group:GroupMode){if(view==="week")return dateKey(new Date(item.startsAt))===columnId;return group==="doctor"?item.doctorId===columnId:item.chairId===columnId;}
function calendarRange(anchor:Date,view:ViewMode){const from=view==="week"?startOfWeek(anchor):startOfDay(anchor),to=new Date(from);to.setDate(to.getDate()+(view==="week"?7:1));return{from:from.toISOString(),to:to.toISOString()};}
function startOfDay(date:Date){const value=new Date(date);value.setHours(0,0,0,0);return value;}
function startOfWeek(date:Date){const value=startOfDay(date);value.setDate(value.getDate()-((value.getDay()+6)%7));return value;}
function weekDays(date:Date){const start=startOfWeek(date);return Array.from({length:7},(_,index)=>{const value=new Date(start);value.setDate(value.getDate()+index);return value;});}
function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function rangeLabel(date:Date,view:ViewMode){if(view==="day")return date.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long",year:"numeric"});const days=weekDays(date);return `${days[0]!.toLocaleDateString("ru-RU",{day:"numeric",month:"short"})} — ${days[6]!.toLocaleDateString("ru-RU",{day:"numeric",month:"short",year:"numeric"})}`;}
function time(date:Date){return date.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});}
function localInput(date:Date){const value=new Date(date);value.setHours(9,0,0,0);return `${dateKey(value)}T09:00`;}
function age(birthDate:string){const birth=new Date(birthDate),today=new Date();let years=today.getFullYear()-birth.getFullYear();if(today < new Date(today.getFullYear(),birth.getMonth(),birth.getDate()))years--;return years;}
function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();}
function money(value:number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency,maximumFractionDigits:0}).format(value/100);}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос";}
