"use client";

import { useCallback,useEffect,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Cashbox {id:string;branchId:string;branchName:string;code:string;name:string;currency:string;hasOpenSession:boolean;openSessionId:string|null;openingAmountMinor:number|null;openedAt:string|null}
interface Category {id:string;organizationId:string;organizationName:string;name:string;currency:string}
interface Named {id:string;name:string;firstName?:string;lastName?:string;phone?:string}
type Modal="expense"|"charge"|null;

export default function FinancePage(){const {session,request}=useAuth();const [cashboxes,setCashboxes]=useState<Cashbox[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [branches,setBranches]=useState<Named[]>([]);const [patients,setPatients]=useState<Named[]>([]);const [modal,setModal]=useState<Modal>(null);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [boxes,nextCategories,nextBranches,nextPatients]=await Promise.all([request<Cashbox[]>("/cashboxes"),request<Category[]>("/expense-categories"),request<Named[]>("/branches"),request<Named[]>("/patients")]);setCashboxes(boxes);setCategories(nextCategories);setBranches(nextBranches);setPatients(nextPatients);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[request]);useEffect(()=>{void load();},[load]);
  const canCash=session.permissions.includes("finance.cashbox.manage"),canExpense=session.permissions.includes("finance.expense.create"),canCharge=session.permissions.includes("finance.charge.create");
  async function openSession(box:Cashbox){const raw=window.prompt(`Остаток в кассе «${box.name}» на начало смены, ${box.currency}`,"0");if(raw===null)return;const amount=amountMinor(raw);if(amount===null){setNotice("Введите корректную сумму");return;}try{await request(`/cashboxes/${box.id}/sessions/open`,{method:"POST",body:JSON.stringify({openingAmountMinor:amount})});await load();setNotice("Кассовая смена открыта");}catch(error){setNotice(message(error));}}
  async function closeSession(box:Cashbox){if(!box.openSessionId)return;const raw=window.prompt(`Фактический остаток в кассе «${box.name}», ${box.currency}`);if(raw===null)return;const amount=amountMinor(raw);if(amount===null){setNotice("Введите корректную сумму");return;}try{await request(`/cash-sessions/${box.openSessionId}/close`,{method:"POST",body:JSON.stringify({closingAmountMinor:amount})});await load();setNotice("Кассовая смена закрыта");}catch(error){setNotice(message(error));}}
  async function createExpense(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element),amount=amountMinor(String(form.get("amount")));if(amount===null)return setNotice("Введите корректную сумму расхода");setSaving(true);try{await request("/expenses",{method:"POST",body:JSON.stringify({branchId:form.get("branchId"),categoryId:form.get("categoryId"),cashboxId:form.get("cashboxId"),amountMinor:amount,description:form.get("description")})});element.reset();setModal(null);setNotice("Расход проведён");}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  async function createCharge(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element),amount=amountMinor(String(form.get("amount")));if(amount===null)return setNotice("Введите корректную сумму начисления");setSaving(true);try{await request("/charges",{method:"POST",body:JSON.stringify({patientId:form.get("patientId"),branchId:form.get("branchId"),currency:"KZT",description:value(form,"description"),items:[{description:form.get("description")||"Услуги клиники",quantity:1,unitPriceMinor:amount}]})});element.reset();setModal(null);setNotice("Начисление создано. Оно появилось в карточке пациента.");}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  return <main className="data-page"><div className="page-heading"><div><span className="eyebrow">Денежные операции</span><h1>Финансы</h1><p>Кассовые смены, начисления пациентам и расходы клиники.</p></div><div className="page-actions">{canExpense&&<button className="secondary" onClick={()=>setModal("expense")}>− Расход</button>}{canCharge&&<button className="primary" onClick={()=>setModal("charge")}>＋ Начисление</button>}</div></div>
    {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <section className="work-metrics"><Metric value={cashboxes.length} label="Касс"/><Metric value={cashboxes.filter(item=>item.hasOpenSession).length} label="Открытых смен"/><Metric value={categories.length} label="Статей расходов"/><Metric value={patients.length} label="Лицевых счетов"/></section>
    <div className="finance-layout"><section className="finance-panel"><div className="panel-heading"><div><span className="eyebrow">Операционный день</span><h2>Кассы</h2></div><span>{cashboxes.filter(item=>item.hasOpenSession).length} активных</span></div>{loading?<div className="inline-empty">Загружаем кассы…</div>:cashboxes.length?<div className="cashbox-list">{cashboxes.map(box=><article key={box.id}><span className={`cashbox-icon ${box.hasOpenSession?"open":""}`}>₸</span><div><b>{box.name}</b><small>{box.branchName} · {box.currency}</small></div><span className={box.hasOpenSession?"session-open":"session-closed"}>{box.hasOpenSession?"Смена открыта":"Смена закрыта"}</span>{box.openedAt&&<time>с {formatTime(box.openedAt)}</time>}{canCash&&(box.hasOpenSession?<button className="secondary" onClick={()=>void closeSession(box)}>Закрыть</button>:<button className="secondary" onClick={()=>void openSession(box)}>Открыть</button>)}</article>)}</div>:<div className="inline-empty">Создайте кассу в справочниках.</div>}</section>
      <aside className="finance-panel"><div className="panel-heading"><div><span className="eyebrow">Учёт</span><h2>Статьи расходов</h2></div></div><div className="category-list">{categories.map(item=><article key={item.id}><span>{item.name}</span><small>{item.organizationName}</small><b>{item.currency}</b></article>)}{!categories.length&&<div className="inline-empty">Нет статей расходов.</div>}</div></aside></div>
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><form className="patient-form-modal" onSubmit={modal==="expense"?createExpense:createCharge} onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Финансы</span><h2>{modal==="expense"?"Провести расход":"Начислить пациенту"}</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></div><div className="patient-form-grid">{modal==="expense"?<><Select name="branchId" label="Филиал" items={branches}/><Select name="cashboxId" label="Касса" items={cashboxes.filter(item=>item.hasOpenSession)}/><Select name="categoryId" label="Статья расхода" items={categories}/><Field name="amount" label="Сумма, ₸" type="number"/><label className="wide">Описание<textarea name="description" rows={3} required/></label></>:<><Select name="patientId" label="Пациент" items={patients}/><Select name="branchId" label="Филиал" items={branches}/><Field name="amount" label="Сумма, ₸" type="number"/><label className="wide">Описание<textarea name="description" rows={3} required placeholder="Консультация, лечение…"/></label></>}</div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>Отмена</button><button className="primary" disabled={saving}>{saving?"Проводим…":modal==="expense"?"Провести расход":"Создать начисление"}</button></div></form></div>}
  </main>}

function Metric({value,label}:{value:number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <label>{label}<input name={name} type={type} min={type==="number"?"0.01":undefined} step={type==="number"?"0.01":undefined} required/></label>}
function Select({name,label,items}:{name:string;label:string;items:(Named|Cashbox|Category)[]}){return <label>{label}<select name={name} defaultValue="" required><option value="" disabled>Выберите</option>{items.map(item=><option value={item.id} key={item.id}>{display(item)}</option>)}</select></label>}
function display(item:Named|Cashbox|Category){if("firstName" in item)return `${item.lastName??""} ${item.firstName??""}`.trim();return item.name}
function value(form:FormData,name:string){return String(form.get(name)||"").trim()||undefined}
function amountMinor(raw:string){const number=Number(raw.replace(",","."));return Number.isFinite(number)&&number>0?Math.round(number*100):null}
function formatTime(value:string){return new Date(value).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос"}
