"use client";

import Link from "next/link";
import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Appointment {id:string;patientId:string;doctorId:string;branchId:string;startsAt:string;endsAt:string;status:string;patientName:string;doctorName:string;chairName?:string;reason?:string|null}
interface Note {id:string;title:string;content:string;status:"draft"|"signed"|"amended";currentVersion:number;signedAt:string|null}
interface Diagnosis {id:string;code:string;name:string;kind:string;toothNumber:number|null}
interface Procedure {id:string;serviceId:string;serviceName:string;toothNumber:number|null;quantity:number;status:string;notes:string|null}
interface Encounter {id:string;appointmentId:string|null;patientId:string;doctorId:string;branchId:string;organizationId?:string;status:string;startedAt:string;completedAt:string|null;patientName?:string;doctorName?:string;appointmentStatus?:string;reason?:string|null;chairName?:string;notesCount?:number;diagnosesCount?:number;proceduresCount?:number;notes?:Note[];diagnoses?:Diagnosis[];procedures?:Procedure[]}
interface OdontogramEntry {id:string;toothNumber:number;surface:string;conditionCode:string;status:string;observedAt:string}
interface Odontogram {patientId:string;entries:OdontogramEntry[];history:unknown[]}
interface Service {id:string;organizationId:string;code:string;name:string;durationMinutes:number}
interface DiagnosisCatalog {id:string;organizationId:string;code:string;name:string}
interface PlanItem {id:string;serviceId:string;serviceName:string;doctorId:string|null;doctorName:string|null;toothNumber:number|null;quantity:number;listPriceMinor:number;discountMinor:number;finalPriceMinor:number;status:string}
interface TreatmentPlan {id:string;organizationId:string;patientId:string;title:string;status:string;currency:string;createdAt:string;proposedAmountMinor:number;acceptedAmountMinor:number;realizedAmountMinor:number;items:PlanItem[]}
type QueueFilter="all"|"waiting"|"active"|"completed";
type ClinicalTab="record"|"odontogram"|"plans";

const statusLabels:Record<string,string>={created:"Создана",awaiting_confirmation:"Ждёт подтверждения",confirmed:"Подтверждена",checked_in:"Пациент пришёл",in_progress:"Идёт приём",completed:"Завершён",cancelled:"Отменён",no_show:"Неявка",rescheduled:"Перенесён"};
const teeth=[[18,17,16,15,14,13,12,11],[21,22,23,24,25,26,27,28],[48,47,46,45,44,43,42,41],[31,32,33,34,35,36,37,38]];
const conditionLabels:Record<string,string>={healthy:"Здоров",caries:"Кариес",filling:"Пломба",crown:"Коронка",missing:"Отсутствует",implant:"Имплант",pulpitis:"Пульпит",periodontitis:"Периодонтит"};

export default function TreatmentPage(){
  const {session,request}=useAuth();const [date,setDate]=useState(todayKey);const [appointments,setAppointments]=useState<Appointment[]>([]);const [encounters,setEncounters]=useState<Encounter[]>([]);
  const [filter,setFilter]=useState<QueueFilter>("all");const [selected,setSelected]=useState<Encounter|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
  const range=useMemo(()=>dayRange(date),[date]);const canWrite=session.permissions.includes("clinical.write");const canUpdateAppointments=session.permissions.includes("appointments.update");
  const load=useCallback(async()=>{setLoading(true);try{const query=`from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`;const [nextAppointments,nextEncounters]=await Promise.all([request<Appointment[]>(`/appointments?${query}`),request<Encounter[]>(`/encounters?${query}`)]);setAppointments(nextAppointments);setEncounters(nextEncounters);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[range,request]);
  useEffect(()=>{void load();},[load]);
  const encounterByAppointment=useMemo(()=>new Map(encounters.filter(item=>item.appointmentId).map(item=>[item.appointmentId!,item])),[encounters]);
  const visible=appointments.filter(item=>matchesFilter(item,encounterByAppointment.get(item.id),filter));
  async function transition(appointment:Appointment,action:string){try{await request(`/appointments/${appointment.id}/${action}`,{method:"POST",body:"{}"});await load();}catch(error){setNotice(message(error));}}
  async function startEncounter(appointment:Appointment){setSaving(true);try{if(appointment.status==="checked_in")await request(`/appointments/${appointment.id}/start`,{method:"POST",body:"{}"});const created=await request<Encounter>("/encounters",{method:"POST",body:JSON.stringify({patientId:appointment.patientId,doctorId:appointment.doctorId,branchId:appointment.branchId,appointmentId:appointment.id})});setSelected({...created,patientName:appointment.patientName,doctorName:appointment.doctorName});await load();}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  function moveDate(days:number){setDate(current=>{const next=new Date(`${current}T12:00:00`);next.setDate(next.getDate()+days);return localDateKey(next);});}
  return <main className="data-page treatment-page"><div className="page-heading"><div><span className="eyebrow">Клиническая работа</span><h1>Лечение</h1><p>Очередь пациентов, активные приёмы и клинические записи.</p></div><div className="treatment-date"><button className="secondary" onClick={()=>moveDate(-1)} aria-label="Предыдущий день">←</button><label><span>Рабочий день</span><input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button className="secondary" onClick={()=>moveDate(1)} aria-label="Следующий день">→</button><button className="secondary" onClick={()=>setDate(todayKey())}>Сегодня</button></div></div>
    {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<section className="work-metrics"><Metric value={appointments.length} label="Записей"/><Metric value={appointments.filter(item=>item.status==="checked_in").length} label="Ожидают врача"/><Metric value={encounters.filter(item=>item.status==="in_progress").length} label="Активных приёмов"/><Metric value={encounters.filter(item=>item.status==="completed").length} label="Завершено"/></section>
    <div className="treatment-layout"><section className="treatment-queue"><header><div><span className="eyebrow">{formatDay(date)}</span><h2>Очередь приёмов</h2></div><div className="queue-filters">{(["all","waiting","active","completed"] as const).map(key=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{filterLabel(key)}</button>)}</div></header>{loading?<div className="data-empty">Загружаем клиническую очередь…</div>:visible.length===0?<div className="data-empty">Для выбранного фильтра записей нет.</div>:<div className="clinical-list">{visible.map(appointment=>{const encounter=encounterByAppointment.get(appointment.id);return <article key={appointment.id} className={encounter?.status==="in_progress"?"active":""}><time><b>{formatTime(appointment.startsAt)}</b><span>{duration(appointment)} мин</span></time><span className="clinical-avatar">{initials(appointment.patientName)}</span><div className="clinical-person"><Link href={`/patients/${appointment.patientId}`}>{appointment.patientName}</Link><span>{appointment.reason||"Стоматологический приём"}</span><small>{appointment.doctorName}{appointment.chairName?` · ${appointment.chairName}`:""}</small></div><div className="clinical-state"><i data-status={encounter?.status||appointment.status}>{statusLabels[encounter?.status||appointment.status]??encounter?.status??appointment.status}</i>{encounter&&<small>{encounter.notesCount??0} записей · {encounter.diagnosesCount??0} диагнозов</small>}</div><div className="clinical-actions">{encounter?<button className="primary" onClick={()=>setSelected({...encounter,patientName:appointment.patientName,doctorName:appointment.doctorName})}>Открыть приём</button>:appointment.status==="confirmed"&&canUpdateAppointments?<button className="secondary" onClick={()=>void transition(appointment,"check-in")}>Пациент пришёл</button>:["checked_in","in_progress"].includes(appointment.status)&&canWrite?<button className="primary" disabled={saving} onClick={()=>void startEncounter(appointment)}>Начать приём</button>:<Link href={`/patients/${appointment.patientId}`} className="button-link">Карта пациента</Link>}</div></article>})}</div>}</section>
      <aside className="treatment-summary"><span className="eyebrow">Навигация по работе</span><h2>Клинический день</h2><p>Начните приём из очереди, заполните карту зубов, добавьте диагнозы и процедуры, затем подпишите запись.</p><ol><li><b>1</b><span><strong>Пациент прибыл</strong><small>Отметьте приход после подтверждения записи.</small></span></li><li><b>2</b><span><strong>Приём начат</strong><small>Откроются запись, одонтограмма и план лечения.</small></span></li><li><b>3</b><span><strong>Запись подписана</strong><small>После подписи приём можно завершить.</small></span></li></ol><Link href="/patients">Все пациенты →</Link></aside></div>
    {selected&&<ClinicalDrawer encounter={selected} appointment={appointments.find(item=>item.id===selected.appointmentId)} onClose={()=>setSelected(null)} onChanged={load} onNotice={setNotice}/>}</main>;
}

function ClinicalDrawer({encounter:initial,appointment,onClose,onChanged,onNotice}:{encounter:Encounter;appointment:Appointment|undefined;onClose:()=>void;onChanged:()=>Promise<void>;onNotice:(value:string)=>void}){
  const {session,request}=useAuth();const [encounter,setEncounter]=useState<Encounter>(initial);const [odontogram,setOdontogram]=useState<Odontogram|null>(null);const [services,setServices]=useState<Service[]>([]);const [diagnosisCatalog,setDiagnosisCatalog]=useState<DiagnosisCatalog[]>([]);const [plans,setPlans]=useState<TreatmentPlan[]>([]);
  const [tab,setTab]=useState<ClinicalTab>("record");const [selectedTooth,setSelectedTooth]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
  const canWrite=session.permissions.includes("clinical.write"),canSign=session.permissions.includes("clinical.sign"),canPlans=session.permissions.includes("treatment_plans.manage"),canReadPlans=session.permissions.includes("treatment_plans.read"),canCatalog=session.permissions.includes("catalog.read");
  const load=useCallback(async()=>{setLoading(true);try{const detail=await request<Encounter>(`/encounters/${initial.id}`);setEncounter({...detail,...(initial.patientName?{patientName:initial.patientName}:{}),...(initial.doctorName?{doctorName:initial.doctorName}:{})});const [chart,diagnoses,nextServices,nextPlans]=await Promise.all([request<Odontogram>(`/patients/${detail.patientId}/odontogram`),request<DiagnosisCatalog[]>("/diagnoses"),canCatalog?request<Service[]>("/services"):Promise.resolve([] as Service[]),canReadPlans?request<TreatmentPlan[]>(`/treatment-plans?patientId=${detail.patientId}`):Promise.resolve([] as TreatmentPlan[])]);setOdontogram(chart);setDiagnosisCatalog(diagnoses.filter(item=>!detail.organizationId||item.organizationId===detail.organizationId));setServices(nextServices.filter(item=>!detail.organizationId||item.organizationId===detail.organizationId));setPlans(nextPlans);}catch(error){onNotice(message(error));}finally{setLoading(false);}},[canCatalog,canReadPlans,initial.doctorName,initial.id,initial.patientName,onNotice,request]);
  useEffect(()=>{void load();},[load]);
  async function mutate(work:()=>Promise<unknown>,success?:string){setSaving(true);try{await work();await Promise.all([load(),onChanged()]);if(success)onNotice(success);}catch(error){onNotice(message(error));}finally{setSaving(false);}}
  async function createNote(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element);await mutate(()=>request("/clinical-notes",{method:"POST",body:JSON.stringify({encounterId:encounter.id,title:form.get("title"),content:form.get("content")})}));element.reset();}
  async function createDiagnosis(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element),item=diagnosisCatalog.find(value=>value.id===form.get("diagnosisId"));if(!item)return;await mutate(()=>request(`/encounters/${encounter.id}/diagnoses`,{method:"POST",body:JSON.stringify({code:item.code,name:item.name,kind:form.get("kind"),toothNumber:optionalNumber(form,"toothNumber")})}),"Диагноз добавлен");element.reset();}
  async function createProcedure(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element);await mutate(()=>request(`/encounters/${encounter.id}/procedures`,{method:"POST",body:JSON.stringify({serviceId:form.get("serviceId"),toothNumber:optionalNumber(form,"toothNumber"),quantity:Number(form.get("quantity")),notes:optionalText(form,"notes")})}),"Процедура добавлена");element.reset();}
  async function saveTooth(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedTooth)return;const form=new FormData(event.currentTarget);await mutate(()=>request(`/patients/${encounter.patientId}/odontogram/entries`,{method:"POST",body:JSON.stringify({encounterId:encounter.id,doctorId:encounter.doctorId,toothNumber:selectedTooth,surface:form.get("surface"),conditionCode:form.get("conditionCode"),status:form.get("status")})}),"Одонтограмма обновлена");setSelectedTooth(null);}
  async function createPlan(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!encounter.organizationId)return;const element=event.currentTarget,form=new FormData(element),quantity=Number(form.get("quantity")),listPriceMinor=toMinor(form.get("price")),discountMinor=toMinor(form.get("discount"));await mutate(()=>request("/treatment-plans",{method:"POST",body:JSON.stringify({organizationId:encounter.organizationId,patientId:encounter.patientId,title:form.get("title"),currency:"KZT",items:[{serviceId:form.get("serviceId"),doctorId:encounter.doctorId,toothNumber:optionalNumber(form,"toothNumber"),quantity,listPriceMinor,discountMinor,finalPriceMinor:listPriceMinor*quantity-discountMinor}]})}),"План лечения создан");element.reset();}
  async function completeEncounter(){setSaving(true);try{await request(`/encounters/${encounter.id}/complete`,{method:"POST",body:"{}"});if(encounter.appointmentId&&appointment?.status==="in_progress")await request(`/appointments/${encounter.appointmentId}/complete`,{method:"POST",body:"{}"});await onChanged();onNotice("Приём завершён");onClose();}catch(error){onNotice(message(error));}finally{setSaving(false);}}
  const toothEntries=useMemo(()=>new Map(odontogram?.entries.filter(item=>item.status==="active").map(item=>[item.toothNumber,item])??[]),[odontogram]);
  return <div className="modal-backdrop side" onMouseDown={onClose}><aside className="task-drawer encounter-drawer" onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Клинический приём</span><h2>{encounter.patientName||appointment?.patientName||"Пациент"}</h2></div><button onClick={onClose}>×</button></div><div className="encounter-meta"><span>{statusLabels[encounter.status]??encounter.status}</span><time>{formatDateTime(encounter.startedAt)}</time><Link href={`/patients/${encounter.patientId}`}>Карта пациента ↗</Link></div><nav className="clinical-tabs" aria-label="Разделы приёма"><button className={tab==="record"?"active":""} onClick={()=>setTab("record")}>Приём</button><button className={tab==="odontogram"?"active":""} onClick={()=>setTab("odontogram")}>Одонтограмма <span>{odontogram?.entries.length??0}</span></button><button className={tab==="plans"?"active":""} onClick={()=>setTab("plans")}>Планы <span>{plans.length}</span></button></nav>
    {loading?<div className="drawer-empty">Загружаем клинические данные…</div>:tab==="record"?<RecordTab encounter={encounter} services={services} diagnoses={diagnosisCatalog} canWrite={canWrite} canSign={canSign} saving={saving} createNote={createNote} createDiagnosis={createDiagnosis} createProcedure={createProcedure} signNote={note=>mutate(()=>request(`/clinical-notes/${note.id}/sign`,{method:"POST",body:"{}"}),"Запись подписана")} completeProcedure={procedure=>mutate(()=>request(`/procedures/${procedure.id}/complete`,{method:"POST",body:"{}"}),"Процедура завершена")} completeEncounter={completeEncounter}/>:tab==="odontogram"?<OdontogramTab entries={toothEntries} selectedTooth={selectedTooth} setSelectedTooth={setSelectedTooth} canWrite={canWrite&&encounter.status==="in_progress"} saving={saving} save={saveTooth}/>:<PlansTab plans={plans} services={services} canManage={canPlans&&encounter.status==="in_progress"} saving={saving} create={createPlan} present={plan=>mutate(()=>request(`/treatment-plans/${plan.id}/present`,{method:"POST",body:"{}"}),"План представлен пациенту")} accept={plan=>mutate(()=>request(`/treatment-plans/${plan.id}/accept`,{method:"POST",body:JSON.stringify({itemIds:plan.items.filter(item=>item.status==="proposed").map(item=>item.id),acceptedBy:"patient"})}),"План принят")}/>}</aside></div>;
}

function RecordTab({encounter,services,diagnoses,canWrite,canSign,saving,createNote,createDiagnosis,createProcedure,signNote,completeProcedure,completeEncounter}:{encounter:Encounter;services:Service[];diagnoses:DiagnosisCatalog[];canWrite:boolean;canSign:boolean;saving:boolean;createNote:(event:FormEvent<HTMLFormElement>)=>Promise<void>;createDiagnosis:(event:FormEvent<HTMLFormElement>)=>Promise<void>;createProcedure:(event:FormEvent<HTMLFormElement>)=>Promise<void>;signNote:(note:Note)=>Promise<void>;completeProcedure:(procedure:Procedure)=>Promise<void>;completeEncounter:()=>Promise<void>}){
  const active=encounter.status==="in_progress";return <><section className="encounter-section"><header><h3>Клинические записи</h3><span>{encounter.notes?.length??0}</span></header>{encounter.notes?.length?<div className="clinical-notes">{encounter.notes.map(note=><article key={note.id}><div><b>{note.title}</b><span className={`note-status ${note.status}`}>{noteStatus(note.status)}</span></div><p>{note.content}</p><footer><small>Версия {note.currentVersion}</small>{note.status==="draft"&&canSign&&<button className="secondary" disabled={saving} onClick={()=>void signNote(note)}>Подписать</button>}</footer></article>)}</div>:<div className="drawer-empty">Записей пока нет.</div>}</section>
    {active&&canWrite&&<form className="clinical-note-form" onSubmit={createNote}><h3>Новая запись</h3><label>Заголовок<input name="title" defaultValue="Осмотр и лечение" required/></label><label>Содержание<textarea name="content" rows={5} placeholder="Жалобы, анамнез, объективные данные, выполненное лечение и рекомендации" required/></label><button className="primary" disabled={saving}>{saving?"Сохраняем…":"Сохранить запись"}</button></form>}
    <div className="clinical-work-grid"><section className="encounter-section compact"><header><h3>Диагнозы</h3><span>{encounter.diagnoses?.length??0}</span></header>{encounter.diagnoses?.map(item=><article className="clinical-fact" key={item.id}><span><b>{item.code}</b>{item.name}</span><small>{item.toothNumber?`Зуб ${item.toothNumber} · `:""}{diagnosisKind(item.kind)}</small></article>)}{active&&canWrite&&diagnoses.length>0&&<form className="inline-clinical-form" onSubmit={createDiagnosis}><select name="diagnosisId" required defaultValue=""><option value="" disabled>Диагноз</option>{diagnoses.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><div><input name="toothNumber" type="number" min="11" max="85" placeholder="Зуб"/><select name="kind" defaultValue="primary"><option value="primary">Основной</option><option value="secondary">Сопутствующий</option><option value="differential">Предварительный</option></select></div><button className="secondary" disabled={saving}>Добавить диагноз</button></form>}</section>
      <section className="encounter-section compact"><header><h3>Процедуры</h3><span>{encounter.procedures?.length??0}</span></header>{encounter.procedures?.map(item=><article className="clinical-fact" key={item.id}><span><b>{item.serviceName}</b>{item.toothNumber?`Зуб ${item.toothNumber}`:"Без привязки к зубу"}</span><small>{procedureStatus(item.status)} · {item.quantity} ед.</small>{active&&canWrite&&item.status!=="completed"&&<button className="secondary" onClick={()=>void completeProcedure(item)}>Завершить</button>}</article>)}{active&&canWrite&&services.length>0&&<form className="inline-clinical-form" onSubmit={createProcedure}><select name="serviceId" required defaultValue=""><option value="" disabled>Услуга</option>{services.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><div><input name="toothNumber" type="number" min="11" max="85" placeholder="Зуб"/><input name="quantity" type="number" min="1" max="100" defaultValue="1"/></div><input name="notes" placeholder="Комментарий"/><button className="secondary" disabled={saving}>Добавить процедуру</button></form>}</section></div>
    {active&&canWrite&&<div className="encounter-complete"><p>Для завершения нужна хотя бы одна подписанная клиническая запись.</p><button className="primary" disabled={saving||!encounter.notes?.some(note=>["signed","amended"].includes(note.status))} onClick={()=>void completeEncounter()}>Завершить приём</button></div>}</>;
}

function OdontogramTab({entries,selectedTooth,setSelectedTooth,canWrite,saving,save}:{entries:Map<number,OdontogramEntry>;selectedTooth:number|null;setSelectedTooth:(value:number|null)=>void;canWrite:boolean;saving:boolean;save:(event:FormEvent<HTMLFormElement>)=>Promise<void>}){
  const selected=selectedTooth?entries.get(selectedTooth):undefined;return <section className="odontogram-workspace"><div className="odontogram-legend"><span><i data-condition="healthy"/>Здоров</span><span><i data-condition="caries"/>Кариес</span><span><i data-condition="filling"/>Пломба</span><span><i data-condition="crown"/>Коронка</span><span><i data-condition="missing"/>Отсутствует</span><span><i data-condition="implant"/>Имплант</span></div><div className="teeth-chart">{teeth.map((row,index)=><div className={`teeth-row row-${index}`} key={index}>{row.map(tooth=>{const entry=entries.get(tooth);return <button type="button" key={tooth} className={selectedTooth===tooth?"selected":""} data-condition={entry?.conditionCode||"healthy"} onClick={()=>setSelectedTooth(tooth)}><i>◊</i><b>{tooth}</b></button>})}</div>)}</div>{selectedTooth&&<aside className="tooth-editor"><header><div><span className="eyebrow">Зуб</span><h3>{selectedTooth}</h3></div><button onClick={()=>setSelectedTooth(null)}>×</button></header>{canWrite?<form onSubmit={save}><label>Состояние<select name="conditionCode" defaultValue={selected?.conditionCode||"healthy"}>{Object.entries(conditionLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Поверхность<select name="surface" defaultValue={selected?.surface||"whole"}><option value="whole">Весь зуб</option><option value="occlusal">Окклюзионная</option><option value="mesial">Мезиальная</option><option value="distal">Дистальная</option><option value="buccal">Щёчная</option><option value="lingual">Язычная</option><option value="root">Корень</option></select></label><label>Статус<select name="status" defaultValue={selected?.status||"active"}><option value="active">Актуально</option><option value="resolved">Устранено</option></select></label><button className="primary" disabled={saving}>{saving?"Сохраняем…":"Сохранить"}</button></form>:<p>Изменение доступно только во время активного приёма.</p>}</aside>}</section>;
}

function PlansTab({plans,services,canManage,saving,create,present,accept}:{plans:TreatmentPlan[];services:Service[];canManage:boolean;saving:boolean;create:(event:FormEvent<HTMLFormElement>)=>Promise<void>;present:(plan:TreatmentPlan)=>Promise<void>;accept:(plan:TreatmentPlan)=>Promise<void>}){
  return <section className="plans-workspace">{plans.length?<div className="treatment-plan-list">{plans.map(plan=><article key={plan.id}><header><div><b>{plan.title}</b><small>{formatDate(plan.createdAt)}</small></div><span data-status={plan.status}>{planStatus(plan.status)}</span></header><div className="plan-items">{plan.items.map(item=><div key={item.id}><span><b>{item.serviceName}</b><small>{item.toothNumber?`Зуб ${item.toothNumber} · `:""}{item.quantity} ед.</small></span><strong>{money(item.finalPriceMinor,plan.currency)}</strong></div>)}</div><footer><span><small>Стоимость</small><b>{money(plan.proposedAmountMinor,plan.currency)}</b></span><div>{canManage&&plan.status==="draft"&&<button className="secondary" onClick={()=>void present(plan)}>Представить</button>}{canManage&&["presented","partially_accepted"].includes(plan.status)&&plan.items.some(item=>item.status==="proposed")&&<button className="primary" onClick={()=>void accept(plan)}>Принять</button>}</div></footer></article>)}</div>:<div className="drawer-empty">Планов лечения пока нет.</div>}{canManage&&services.length>0&&<form className="plan-create-form" onSubmit={create}><h3>Новый план лечения</h3><label>Название<input name="title" defaultValue="План лечения" required/></label><label>Услуга<select name="serviceId" required defaultValue=""><option value="" disabled>Выберите услугу</option>{services.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div><label>Зуб<input name="toothNumber" type="number" min="11" max="85"/></label><label>Количество<input name="quantity" type="number" min="1" max="100" defaultValue="1" required/></label></div><div><label>Цена, ₸<input name="price" type="number" min="0" step="0.01" required/></label><label>Скидка, ₸<input name="discount" type="number" min="0" step="0.01" defaultValue="0" required/></label></div><button className="primary" disabled={saving}>{saving?"Создаём…":"Создать план"}</button></form>}</section>;
}

function Metric({value,label}:{value:number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function todayKey(){return localDateKey(new Date())}
function localDateKey(value:Date){const offset=value.getTimezoneOffset()*60_000;return new Date(value.getTime()-offset).toISOString().slice(0,10)}
function dayRange(key:string){const from=new Date(`${key}T00:00:00`),to=new Date(from);to.setDate(to.getDate()+1);return{from:from.toISOString(),to:to.toISOString()}}
function formatDay(key:string){return new Date(`${key}T12:00:00`).toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"})}
function formatTime(value:string){return new Date(value).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}
function formatDateTime(value:string){return new Date(value).toLocaleString("ru-RU",{day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"})}
function formatDate(value:string){return new Date(value).toLocaleDateString("ru-RU",{day:"numeric",month:"short",year:"numeric"})}
function duration(item:Appointment){return Math.max(0,Math.round((new Date(item.endsAt).getTime()-new Date(item.startsAt).getTime())/60_000))}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function matchesFilter(appointment:Appointment,encounter:Encounter|undefined,filter:QueueFilter){if(filter==="all")return !["cancelled","no_show","rescheduled"].includes(appointment.status);if(filter==="waiting")return ["confirmed","checked_in"].includes(appointment.status)&&!encounter;if(filter==="active")return encounter?.status==="in_progress";return encounter?.status==="completed"||appointment.status==="completed"}
function filterLabel(value:QueueFilter){return({all:"Все",waiting:"Ожидают",active:"В работе",completed:"Завершены"})[value]}
function noteStatus(value:Note["status"]){return({draft:"Черновик",signed:"Подписана",amended:"Дополнена"})[value]}
function diagnosisKind(value:string){return({primary:"Основной",secondary:"Сопутствующий",differential:"Предварительный"} as Record<string,string>)[value]??value}
function procedureStatus(value:string){return({planned:"Запланирована",in_progress:"В работе",completed:"Выполнена",cancelled:"Отменена"} as Record<string,string>)[value]??value}
function planStatus(value:string){return({draft:"Черновик",presented:"Представлен",partially_accepted:"Частично принят",accepted:"Принят",in_progress:"В работе",completed:"Завершён",cancelled:"Отменён"} as Record<string,string>)[value]??value}
function optionalNumber(form:FormData,name:string){const value=String(form.get(name)||"").trim();return value?Number(value):undefined}
function optionalText(form:FormData,name:string){return String(form.get(name)||"").trim()||undefined}
function toMinor(value:FormDataEntryValue|null){return Math.round(Number(value||0)*100)}
function money(value:number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency,maximumFractionDigits:0}).format(value/100)}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос"}
