export enum ApiErrorCode {
  // General errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',

  // Tenant & Organization
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  CROSS_TENANT_ACCESS_DENIED = 'CROSS_TENANT_ACCESS_DENIED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  CHAIR_NOT_FOUND = 'CHAIR_NOT_FOUND',
  CHAIR_OCCUPIED = 'CHAIR_OCCUPIED',

  // Identity & Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  MFA_REQUIRED = 'MFA_REQUIRED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Clinical & Scheduling
  APPOINTMENT_RESOURCE_CONFLICT = 'APPOINTMENT_RESOURCE_CONFLICT',
  APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_INVALID_STATUS_TRANSITION = 'APPOINTMENT_INVALID_STATUS_TRANSITION',
  CLINICAL_NOTE_ALREADY_SIGNED = 'CLINICAL_NOTE_ALREADY_SIGNED',

  // Audit
  AUDIT_LOG_TAMPERED = 'AUDIT_LOG_TAMPERED',
  AUDIT_LOG_IMMUTABLE = 'AUDIT_LOG_IMMUTABLE'
}

export interface ApiErrorResponse {
  error: {
    code: ApiErrorCode | string;
    message: string;
    details?: Record<string, unknown> | Array<unknown>;
    requestId?: string;
    timestamp?: string;
  };
}
