"use client";

import Link from "next/link";
import { useCallback,useEffect,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Patient{id:string;firstName:string;lastName:string;middleName?:string;birthDate?:string;sex:"female"|"male"|"unknown";phone:string;email?:string;notes?:string;createdAt:string}
interface Balance{patientId:string;balances:{currency:string;balanceMinor:number}[]}
interface LedgerRow{id:string;amountMinor:number;memo?:string;description?:string;currency:string;postedAt:string;transactionType?:string}
interface Deposit{id:string;currency:string;originalAmountMinor:number;availableAmountMinor:number;createdAt:string}
interface Odontogram{entries:{id:string;toothNumber:number;surface:string;conditionCode:string;status:string;observedAt:string}[];history:unknown[]}
type Tab="overview"|"chart"|"perio"|"plan"|"visits"|"images"|"documents"|"finance";
const tabs:[Tab,string][]=[["overview","Обзор"],["chart","Зубная карта"],["perio","Пародонтология"],["plan","План лечения"],["visits","Визиты"],["images","Снимки"],["documents","Документы"],["finance","Финансы"]];

export function PatientWorkspace({patientId}:{patientId:string}){const {session,request}=useAuth();const [patient,setPatient]=useState<Patient|null>(null),[balance,setBalance]=useState<Balance|null>(null),[ledger,setLedger]=useState<LedgerRow[]>([]),[deposits,setDeposits]=useState<Deposit[]>([]),[odontogram,setOdontogram]=useState<Odontogram|null>(null);
  const [tab,setTab]=useState<Tab>("overview"),[editing,setEditing]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");const canFinance=session.permissions.includes("finance.read"),canClinical=session.permissions.includes("clinical.read");
  const load=useCallback(async()=>{setLoading(true);try{const main=await request<Patient>(`/patients/${patientId}`);setPatient(main);if(canFinance){const [nextBalance,nextLedger,nextDeposits]=await Promise.all([request<Balance>(`/patients/${patientId}/balance`),request<LedgerRow[]>(`/patients/${patientId}/ledger`),request<Deposit[]>(`/patients/${patientId}/deposits`)]);setBalance(nextBalance);setLedger(nextLedger);setDeposits(nextDeposits);}if(canClinical)setOdontogram(await request<Odontogram>(`/patients/${patientId}/odontogram`));setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[canClinical,canFinance,patientId,request]);
  useEffect(()=>{void load();},[load]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!patient)return;const form=new FormData(event.currentTarget),optional=(name:string)=>String(form.get(name)??"").trim()||undefined;setSaving(true);try{const updated=await request<Patient>(`/patients/${patient.id}`,{method:"PATCH",body:JSON.stringify({lastName:String(form.get("lastName")),firstName:String(form.get("firstName")),middleName:optional("middleName"),birthDate:optional("birthDate"),sex:String(form.get("sex")),phone:String(form.get("phone")),email:optional("email"),notes:optional("notes")})});setPatient(updated);setEditing(false);setNotice("Карточка пациента обновлена");}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  if(loading&&!patient)return <main className="patient-workspace-page"><div className="data-empty tall">Загружаем карточку пациента…</div></main>;
  if(!patient)return <main className="patient-workspace-page"><div className="data-empty tall"><b>Карточка недоступна</b><span>{notice||"Пациент не найден"}</span><Link href="/patients">Вернуться к списку</Link></div></main>;
  const name=`${patient.lastName} ${patient.firstName}${patient.middleName?` ${patient.middleName}`:""}`;
  return <main className="patient-workspace-page"><div className="patient-breadcrumb"><Link href="/patients">Пациенты</Link><span>›</span><span>{name}</span></div>
    <header className="patient-workspace-header"><div className="patient-identity"><span className="patient-hero-avatar">{initials(patient)}</span><div><div className="patient-name-line"><h1>{name}</h1><span className="status-badge" data-status="active"><i/>Активен</span></div><div className="patient-demographics"><span>ИИН <b>не указан</b></span><span>{patient.birthDate?<><b>{age(patient.birthDate)} лет</b> · {formatDate(patient.birthDate)}</>:"Дата рождения не указана"}</span><a href={`tel:${patient.phone}`}>{patient.phone}</a></div></div></div><div className="patient-header-actions"><Link className="primary button-link" href="/">＋ Новая запись</Link><button className="secondary" onClick={()=>setNotice("Создание плана лечения доступно в разделе «Лечение»")}>Новый план лечения</button><button className="secondary" onClick={()=>setTab("documents")}>Добавить документ</button><button className="icon-button" aria-label="Ещё">•••</button></div></header>
    <div className="patient-alert-bar"><span>!</span><div><b>Медицинские предупреждения</b><small>Активных предупреждений нет</small></div><button onClick={()=>setEditing(true)}>Добавить</button></div>
    {notice&&<div className="toast-notice"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
    <nav className="patient-workspace-tabs" aria-label="Разделы пациента">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    <div className="patient-workspace-layout"><section className="patient-main-panel">
      {tab==="overview"&&<><PanelHeading title="Обзор пациента" subtitle="Основные данные и клинический контекст" action={session.permissions.includes("patients.update")?<button onClick={()=>setEditing(true)}>Изменить</button>:undefined}/><div className="overview-summary"><Metric label="Баланс" value={balance?.balances.length?balance.balances.map(item=>money(item.balanceMinor,item.currency)).join(" · "):"0 ₸"}/><Metric label="Активный план" value="Нет"/><Metric label="Последний визит" value="Нет данных"/><Metric label="Следующий визит" value="Не назначен"/></div><div className="workspace-section"><h3>Контактные и личные данные</h3><dl className="info-grid"><Info label="ФИО" value={name}/><Info label="Телефон" value={patient.phone}/><Info label="Email" value={patient.email||"Не указан"}/><Info label="Дата рождения" value={patient.birthDate?formatDate(patient.birthDate):"Не указана"}/><Info label="Пол" value={sexLabel(patient.sex)}/><Info label="Дата регистрации" value={formatDate(patient.createdAt)}/></dl></div><div className="workspace-section"><h3>Заметки</h3><p className={patient.notes?"patient-notes":"patient-notes muted"}>{patient.notes||"Заметок о пациенте пока нет."}</p></div></>}
      {tab==="chart"&&<><PanelHeading title="Зубная карта" subtitle={`${odontogram?.entries.length??0} клинических отметок`}/>{!canClinical?<Empty title="Нет доступа" text="Недостаточно прав для просмотра клинических данных."/>:<div className="workspace-section"><div className="teeth-overview">{Array.from({length:32},(_,index)=>index+1).map(tooth=>{const entry=odontogram?.entries.find(item=>item.toothNumber===tooth);return <div key={tooth} data-condition={entry?.conditionCode}><i>{tooth}</i><b>{entry?.conditionCode||"Без отметок"}</b><small>{entry?`${entry.surface} · ${entry.status}`:"Здоров"}</small></div>})}</div></div>}</>}
      {tab==="finance"&&<><PanelHeading title="Финансы пациента" subtitle="Баланс, депозиты и история операций"/>{!canFinance?<Empty title="Нет доступа" text="Недостаточно прав для просмотра финансов пациента."/>:<><div className="overview-summary"><Metric label="Баланс" value={balance?.balances.length?balance.balances.map(item=>money(item.balanceMinor,item.currency)).join(" · "):"0 ₸"}/><Metric label="Депозиты" value={String(deposits.length)}/><Metric label="Операции" value={String(ledger.length)}/></div><div className="workspace-section"><h3>Операции</h3>{ledger.length?<div className="ledger-list">{ledger.slice().reverse().map(row=><article key={row.id}><span><b>{row.description||row.memo||"Финансовая операция"}</b><small>{formatDate(row.postedAt)}</small></span><strong className={row.amountMinor<0?"negative":""}>{money(row.amountMinor,row.currency)}</strong></article>)}</div>:<Empty title="Операций нет" text="Финансовые операции пациента появятся здесь."/>}</div></>}</>}
      {!["overview","chart","finance"].includes(tab)&&<><PanelHeading title={tabs.find(([key])=>key===tab)?.[1]??"Раздел"} subtitle="Рабочее пространство пациента"/><Empty title={emptyTitle(tab)} text="Раздел готов для данных пациента. Новые записи будут собраны здесь без перехода из карточки."/></>}
    </section><aside className="patient-context-panel"><section><h3>Быстрый контекст</h3><dl><Info label="ID пациента" value={patient.id.slice(0,8).toUpperCase()}/><Info label="Дата регистрации" value={formatDate(patient.createdAt)}/><Info label="Ответственный врач" value="Не назначен"/></dl></section><section><h3>Ближайшие действия</h3><div className="context-action-list"><Link href="/">Создать запись <span>→</span></Link><button onClick={()=>setTab("plan")}>Открыть план лечения <span>→</span></button><button onClick={()=>setTab("finance")}>Проверить баланс <span>→</span></button></div></section><section><h3>Клиническое резюме</h3><div className="context-stat"><span>Отметки в карте</span><b>{odontogram?.entries.length??0}</b></div><div className="context-stat"><span>Изменения</span><b>{odontogram?.history.length??0}</b></div></section></aside></div>
    {editing&&<div className="modal-backdrop" onMouseDown={()=>setEditing(false)}><form className="patient-form-modal" onSubmit={save} onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="page-kicker">Карточка пациента</span><h2>Изменить данные</h2></div><button type="button" onClick={()=>setEditing(false)}>×</button></div><div className="patient-form-grid"><Field name="lastName" label="Фамилия" defaultValue={patient.lastName}/><Field name="firstName" label="Имя" defaultValue={patient.firstName}/><Field name="middleName" label="Отчество" defaultValue={patient.middleName} optional/><Field name="birthDate" label="Дата рождения" type="date" defaultValue={patient.birthDate} optional/><label>Пол<select name="sex" defaultValue={patient.sex}><option value="unknown">Не указан</option><option value="female">Женский</option><option value="male">Мужской</option></select></label><Field name="phone" label="Телефон" type="tel" defaultValue={patient.phone}/><Field name="email" label="Email" type="email" defaultValue={patient.email} optional/><label className="wide">Заметки <small>необязательно</small><textarea name="notes" rows={4} defaultValue={patient.notes}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEditing(false)}>Отмена</button><button className="primary" disabled={saving}>{saving?"Сохраняем…":"Сохранить"}</button></div></form></div>}
  </main>;
}
function PanelHeading({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <header className="panel-heading patient-panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</header>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="workspace-empty"><span>＋</span><b>{title}</b><p>{text}</p></div>}
function Field({name,label,type="text",optional=false,defaultValue}:{name:string;label:string;type?:string;optional?:boolean;defaultValue?:string|undefined}){return <label>{label}{optional&&<small>необязательно</small>}<input name={name} type={type} defaultValue={defaultValue} required={!optional}/></label>}
function emptyTitle(tab:Tab){return({perio:"Пародонтологические записи отсутствуют",plan:"План лечения не создан",visits:"История визитов пуста",images:"Снимки не загружены",documents:"Документы не добавлены",overview:"",chart:"",finance:""})[tab]}
function initials(patient:Patient){return `${patient.lastName[0]??""}${patient.firstName[0]??""}`.toUpperCase()}
function sexLabel(value:Patient["sex"]){return value==="female"?"Женский":value==="male"?"Мужской":"Не указан"}
function formatDate(value:string){return new Date(value).toLocaleDateString("ru-RU")}
function age(value:string){const birth=new Date(value),today=new Date();let years=today.getFullYear()-birth.getFullYear();if(today<new Date(today.getFullYear(),birth.getMonth(),birth.getDate()))years--;return years;}
function money(value:number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency,maximumFractionDigits:0}).format(value/100)}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось загрузить данные"}
