"use client";

import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Warehouse {id:string;name:string;organizationId:string;branchId:string|null}
interface Product {id:string;name:string;sku:string;symbol:string;minimumStock:number;barcodes:string[]}
interface Supplier {id:string;name:string}
interface Stock {warehouseId:string;warehouseName:string;productId:string;sku:string;name:string;minimumStock:number;symbol:string;batchId:string|null;lotNumber:string|null;expiresAt:string|null;quantity:number}
interface Alert {warehouseId:string;warehouseName:string;productId:string;productName:string;batchId:string|null;lotNumber:string|null;expiresAt:string|null;quantity:number;alertType:"expired"|"expiring"|"low_stock"}

export default function InventoryPage(){const {session,request}=useAuth();const [stock,setStock]=useState<Stock[]>([]);const [alerts,setAlerts]=useState<Alert[]>([]);const [warehouses,setWarehouses]=useState<Warehouse[]>([]);const [products,setProducts]=useState<Product[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [warehouse,setWarehouse]=useState("");const [query,setQuery]=useState("");const [showReceipt,setShowReceipt]=useState(false);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [nextStock,nextAlerts,nextWarehouses,nextProducts,nextSuppliers]=await Promise.all([request<Stock[]>("/inventory/stock"),request<Alert[]>("/inventory/alerts?days=30"),request<Warehouse[]>("/inventory/warehouses"),request<Product[]>("/inventory/products"),request<Supplier[]>("/inventory/suppliers")]);setStock(nextStock);setAlerts(nextAlerts);setWarehouses(nextWarehouses);setProducts(nextProducts);setSuppliers(nextSuppliers);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[request]);useEffect(()=>{void load();},[load]);
  const rows=useMemo(()=>{const needle=query.trim().toLowerCase();return stock.filter(item=>(!warehouse||item.warehouseId===warehouse)&&(!needle||`${item.name} ${item.sku} ${item.lotNumber??""}`.toLowerCase().includes(needle)))},[query,stock,warehouse]);const totalProducts=new Set(stock.map(item=>item.productId)).size;
  async function receive(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element),price=String(form.get("purchasePrice")||"");setSaving(true);try{await request("/stock/receipts",{method:"POST",body:JSON.stringify({warehouseId:form.get("warehouseId"),supplierId:value(form,"supplierId"),reference:value(form,"reference"),items:[{productId:form.get("productId"),quantity:Number(form.get("quantity")),lotNumber:value(form,"lotNumber"),expiresAt:value(form,"expiresAt"),purchasePriceMinor:price?Math.round(Number(price)*100):undefined,currency:"KZT"}]})});element.reset();setShowReceipt(false);await load();setNotice("Поступление проведено, остатки обновлены");}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  return <main className="data-page"><div className="page-heading"><div><span className="eyebrow">Материалы клиники</span><h1>Склад</h1><p>Остатки по складам, партии, сроки годности и критические позиции.</p></div>{session.permissions.includes("inventory.receive")&&<button className="primary" onClick={()=>setShowReceipt(true)}>＋ Поступление</button>}</div>
    {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <section className="work-metrics"><Metric value={warehouses.length} label="Складов"/><Metric value={totalProducts} label="Позиций в наличии"/><Metric value={alerts.filter(item=>item.alertType==="low_stock").length} label="Ниже минимума" danger/><Metric value={alerts.filter(item=>item.alertType!=="low_stock").length} label="Истекает срок" danger/></section>
    {alerts.length>0&&<section className="inventory-alerts"><header><b>Требуют внимания</b><span>{alerts.length}</span></header><div>{alerts.slice(0,6).map((item,index)=><article key={`${item.productId}-${item.warehouseId}-${item.batchId??index}`}><i className={item.alertType}>!</i><span><b>{item.productName}</b><small>{item.warehouseName}{item.lotNumber?` · партия ${item.lotNumber}`:""}</small></span><strong>{alertLabel(item)}</strong></article>)}</div></section>}
    <section className="inventory-panel"><div className="inventory-toolbar"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Название, артикул или партия"/></label><select value={warehouse} onChange={event=>setWarehouse(event.target.value)}><option value="">Все склады</option>{warehouses.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
      {loading?<div className="data-empty">Загружаем остатки…</div>:rows.length?<div className="stock-table"><div className="stock-head"><span>Материал</span><span>Склад</span><span>Партия</span><span>Срок годности</span><span>Остаток</span></div>{rows.map((item,index)=><article key={`${item.warehouseId}-${item.productId}-${item.batchId??index}`}><span><b>{item.name}</b><small>{item.sku}</small></span><span>{item.warehouseName}</span><span>{item.lotNumber||"—"}</span><span className={item.expiresAt&&new Date(item.expiresAt)<new Date()?"stock-expired":""}>{item.expiresAt?formatDate(item.expiresAt):"—"}</span><strong className={item.quantity<item.minimumStock?"stock-low":""}>{formatQuantity(item.quantity)} {item.symbol}</strong></article>)}</div>:<div className="data-empty"><b>Остатков нет</b><span>Проведите первое поступление материалов.</span></div>}
    </section>
    {showReceipt&&<div className="modal-backdrop" onMouseDown={()=>setShowReceipt(false)}><form className="patient-form-modal" onSubmit={receive} onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Складской документ</span><h2>Новое поступление</h2></div><button type="button" onClick={()=>setShowReceipt(false)}>×</button></div><div className="patient-form-grid"><Select name="warehouseId" label="Склад" items={warehouses}/><Select name="supplierId" label="Поставщик" items={suppliers} optional/><Select name="productId" label="Материал" items={products}/><Field name="quantity" label="Количество" type="number"/><Field name="lotNumber" label="Номер партии" optional/><Field name="expiresAt" label="Срок годности" type="date" optional/><Field name="purchasePrice" label="Цена закупки, ₸" type="number" optional/><Field name="reference" label="Накладная" optional/></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setShowReceipt(false)}>Отмена</button><button className="primary" disabled={saving}>{saving?"Проводим…":"Провести поступление"}</button></div></form></div>}
  </main>}

function Metric({value,label,danger=false}:{value:number;label:string;danger?:boolean}){return <div className={danger&&value>0?"danger":""}><b>{value}</b><span>{label}</span></div>}
function Field({name,label,type="text",optional=false}:{name:string;label:string;type?:string;optional?:boolean}){return <label>{label}{optional&&<small>необязательно</small>}<input name={name} type={type} min={type==="number"?"0":undefined} step={type==="number"?"0.001":undefined} required={!optional}/></label>}
function Select({name,label,items,optional=false}:{name:string;label:string;items:{id:string;name:string}[];optional?:boolean}){return <label>{label}{optional&&<small>необязательно</small>}<select name={name} defaultValue="" required={!optional}><option value="">{optional?"Не выбран":"Выберите"}</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
function value(form:FormData,name:string){return String(form.get(name)||"").trim()||undefined}
function alertLabel(item:Alert){if(item.alertType==="low_stock")return `Остаток ${formatQuantity(item.quantity)}`;if(item.alertType==="expired")return "Срок истёк";return item.expiresAt?`до ${formatDate(item.expiresAt)}`:"Истекает"}
function formatDate(value:string){return new Date(value).toLocaleDateString("ru-RU")}
function formatQuantity(value:number){return new Intl.NumberFormat("ru-RU",{maximumFractionDigits:3}).format(value)}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос"}
