import Link from "next/link";
import { ArrowLeft, Coins } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { defaultAnalyticsDates } from "@/modules/analytics/schemas";
import { getOrganizationContext } from "@/modules/organizations/repository";
import { PayrollManager } from "@/modules/payroll/payroll-manager";
import { getCompensationReferenceData, getCompensationReport, listCompensationEntries, listCompensationRules } from "@/modules/payroll/repository";
import { compensationPeriodSchema } from "@/modules/payroll/schemas";

export default async function PayrollPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const query = await searchParams; const defaults = defaultAnalyticsDates(); const parsed = compensationPeriodSchema.safeParse({ from: query.from ?? defaults.from, to: query.to ?? defaults.to }); const period = parsed.success ? parsed.data : defaults;
  const [references, rules, report, entries, context] = await Promise.all([getCompensationReferenceData(), listCompensationRules(), getCompensationReport(period.from, period.to), listCompensationEntries(period.from, period.to), getOrganizationContext()]); if (!context) return null;
  const money = new Intl.NumberFormat("ru-KZ", { style: "currency", currency: context.organization.currency, maximumFractionDigits: 2 }); const date = new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "short", year: "numeric", timeZone: context.organization.timezone }); const total = report.reduce((sum, row) => sum + row.compensationAmount, 0);
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/finance" className="mb-3 inline-flex items-center gap-1 text-xs font-medium text-[var(--muted)] hover:text-[var(--foreground)]"><ArrowLeft className="size-3.5" />Финансы</Link><p className="text-sm font-semibold text-[var(--brand)]">Расчётный контур</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.04em]">Вознаграждения врачей</h1><p className="mt-2 text-sm text-[var(--muted)]">Версионные ставки и зафиксированные начисления без пересчёта истории.</p></div><form className="flex flex-wrap items-end gap-2"><label className="space-y-1"><span className="text-xs text-[var(--muted)]">С даты</span><input name="from" type="date" defaultValue={period.from} className="block h-10 rounded-xl border bg-white px-3 text-sm" /></label><label className="space-y-1"><span className="text-xs text-[var(--muted)]">По дату</span><input name="to" type="date" defaultValue={period.to} className="block h-10 rounded-xl border bg-white px-3 text-sm" /></label><Button>Показать</Button></form></div>
    <div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><Coins className="size-5 text-[var(--brand)]" /><p className="mt-3 text-2xl font-semibold">{money.format(total)}</p><p className="mt-1 text-xs text-[var(--muted)]">начислено за период</p></Card><Card className="p-5"><p className="text-sm text-[var(--muted)]">Врачей в расчёте</p><p className="mt-3 text-2xl font-semibold">{report.length}</p></Card><Card className="p-5"><p className="text-sm text-[var(--muted)]">Зафиксировано услуг</p><p className="mt-3 text-2xl font-semibold">{report.reduce((sum, row) => sum + row.entriesCount, 0)}</p></Card></div>
    <Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Начисления за период</h2></div>{report.length === 0 ? <p className="p-7 text-center text-sm text-[var(--muted)]">Начисления ещё не зафиксированы.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[var(--surface-muted)] text-xs text-[var(--muted)]"><tr>{["Врач", "Услуг", "Выручка", "Материалы", "База после материалов", "Вознаграждение"].map((item) => <th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y">{report.map((row) => <tr key={row.employeeId}><td className="px-4 py-4 font-semibold">{row.employeeName}</td><td className="px-4 py-4">{row.entriesCount}</td><td className="px-4 py-4">{money.format(row.revenueAmount)}</td><td className="px-4 py-4">{money.format(row.materialCostAmount)}</td><td className="px-4 py-4">{money.format(row.revenueAmount - row.materialCostAmount)}</td><td className="px-4 py-4 font-semibold text-[var(--brand-dark)]">{money.format(row.compensationAmount)}</td></tr>)}</tbody></table></div>}</Card>
    {entries.length > 0 && <Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Расшифровка начислений</h2><p className="mt-1 text-xs text-[var(--muted)]">Ставка и база сохранены в момент проведения.</p></div><div className="max-h-[520px] overflow-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="sticky top-0 bg-[var(--surface-muted)] text-xs text-[var(--muted)]"><tr>{["Дата", "Врач / услуга", "Кол-во", "Ставка", "Выручка", "Материалы", "База", "Начислено"].map((item) => <th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y">{entries.map((entry) => <tr key={entry.id}><td className="px-4 py-4 whitespace-nowrap">{date.format(new Date(entry.performedAt))}</td><td className="px-4 py-4"><p className="font-semibold">{entry.employeeName}</p><p className="mt-1 text-xs text-[var(--muted)]">{entry.serviceName}</p></td><td className="px-4 py-4">{entry.quantity}</td><td className="px-4 py-4">{entry.ruleType === "fixed_per_service" ? money.format(entry.ruleValue) : `${entry.ruleValue}%`}</td><td className="px-4 py-4">{money.format(entry.revenueAmount)}</td><td className="px-4 py-4">{money.format(entry.materialCostAmount)}</td><td className="px-4 py-4">{money.format(entry.calculationBase)}</td><td className="px-4 py-4 font-semibold">{money.format(entry.compensationAmount)}</td></tr>)}</tbody></table></div></Card>}
    <PayrollManager references={references} rules={rules} from={period.from} to={period.to} canManage={context.can("payroll.manage")} />
  </div>;
}
