"use client";

import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { useAuth } from "../../auth-shell";

interface Named {id:string;name:string;organizationId?:string}
interface Lead {id:string;organizationId:string;branchId:string|null;firstName:string;lastName:string|null;phone:string;email:string|null;interest:string|null;notes:string|null;status:"new"|"qualified"|"converted"|"lost";sourceName?:string;channelName?:string;branchName?:string;lostReason?:string;createdAt:string}
interface Stage {id:string;name:string;key:string;position:number;isTerminal:boolean;terminalKind?:"won"|"lost"}
interface Opportunity {id:string;title:string;patientId:string;stageId:string|null;stageName?:string;stageKey?:string;expectedAmountMinor:number|null;currency:string;status:string;patientName?:string;createdAt:string}
type View="leads"|"pipeline";

export default function CrmPage(){const {session,request}=useAuth();const [view,setView]=useState<View>("leads");const [leads,setLeads]=useState<Lead[]>([]);const [opportunities,setOpportunities]=useState<Opportunity[]>([]);const [organizations,setOrganizations]=useState<Named[]>([]);const [branches,setBranches]=useState<Named[]>([]);const [sources,setSources]=useState<Named[]>([]);const [channels,setChannels]=useState<Named[]>([]);const [stages,setStages]=useState<Stage[]>([]);
  const [query,setQuery]=useState("");const [showCreate,setShowCreate]=useState(false);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const canManage=session.permissions.includes("crm.manage");
  const load=useCallback(async()=>{setLoading(true);try{const [nextLeads,nextOpportunities,nextOrganizations,nextBranches,nextSources,nextChannels,nextStages]=await Promise.all([request<Lead[]>("/leads"),request<Opportunity[]>("/opportunities"),request<Named[]>("/organizations"),request<Named[]>("/branches"),request<Named[]>("/crm/lead-sources"),request<Named[]>("/crm/lead-channels"),request<Stage[]>("/crm/opportunity-stages")]);setLeads(nextLeads);setOpportunities(nextOpportunities);setOrganizations(nextOrganizations);setBranches(nextBranches);setSources(nextSources);setChannels(nextChannels);setStages(nextStages);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[request]);useEffect(()=>{void load();},[load]);
  const visibleLeads=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?leads.filter(item=>`${item.firstName} ${item.lastName??""} ${item.phone} ${item.interest??""}`.toLowerCase().includes(needle)):leads},[leads,query]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element);setSaving(true);try{await request("/leads",{method:"POST",body:JSON.stringify({organizationId:form.get("organizationId"),branchId:value(form,"branchId"),sourceId:value(form,"sourceId"),channelId:value(form,"channelId"),firstName:form.get("firstName"),lastName:value(form,"lastName"),phone:form.get("phone"),email:value(form,"email"),interest:value(form,"interest"),notes:value(form,"notes")})});element.reset();setShowCreate(false);await load();setNotice("Обращение создано");}catch(error){setNotice(message(error));}finally{setSaving(false);}}
  async function qualify(lead:Lead){try{await request(`/leads/${lead.id}`,{method:"PATCH",body:JSON.stringify({status:"qualified"})});await load();setNotice(`${lead.firstName}: обращение квалифицировано`);}catch(error){setNotice(message(error));}}
  async function lose(lead:Lead){const reason=window.prompt("Укажите причину потери обращения");if(!reason||reason.trim().length<3)return;try{await request(`/leads/${lead.id}/lose`,{method:"POST",body:JSON.stringify({reason})});await load();setNotice(`${lead.firstName}: обращение закрыто`);}catch(error){setNotice(message(error));}}
  const pipelineStages=stages.length?stages:[{id:"no-stage",name:"Без этапа",key:"unassigned",position:0,isTerminal:false}];
  return <main className="data-page"><div className="page-heading"><div><span className="eyebrow">Работа с обращениями</span><h1>CRM</h1><p>Новые обращения и путь пациента до принятого плана лечения.</p></div>{canManage&&<button className="primary" onClick={()=>setShowCreate(true)}>＋ Новое обращение</button>}</div>
    {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <section className="work-metrics"><Metric value={leads.filter(item=>item.status==="new").length} label="Новых лидов"/><Metric value={leads.filter(item=>item.status==="qualified").length} label="Квалифицировано"/><Metric value={opportunities.length} label="Сделок"/><Metric value={opportunities.reduce((sum,item)=>sum+(item.expectedAmountMinor??0),0)} label="Потенциал, ₸" money/></section>
    <div className="crm-switcher"><button className={view==="leads"?"active":""} onClick={()=>setView("leads")}>Обращения <span>{leads.length}</span></button><button className={view==="pipeline"?"active":""} onClick={()=>setView("pipeline")}>Воронка <span>{opportunities.length}</span></button></div>
    {loading?<div className="data-empty">Загружаем CRM…</div>:view==="leads"?<section className="crm-panel"><div className="crm-toolbar"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Поиск по имени, телефону или интересу"/></label></div>{visibleLeads.length?<div className="lead-list"><div className="lead-head"><span>Контакт</span><span>Интерес</span><span>Источник</span><span>Статус</span><span/></div>{visibleLeads.map(lead=><article className="lead-row" key={lead.id}><span className="lead-person"><i>{lead.firstName[0]}{lead.lastName?.[0]??""}</i><span><b>{lead.firstName} {lead.lastName}</b><small>{lead.phone}{lead.email?` · ${lead.email}`:""}</small></span></span><span>{lead.interest||"Не указан"}</span><span>{lead.sourceName||lead.channelName||"Не указан"}</span><span><i className={`lead-status ${lead.status}`}>{leadStatus(lead.status)}</i></span><span className="lead-actions">{canManage&&lead.status==="new"&&<button onClick={()=>void qualify(lead)}>Квалифицировать</button>}{canManage&&!['lost','converted'].includes(lead.status)&&<button className="danger-link" onClick={()=>void lose(lead)}>Закрыть</button>}</span></article>)}</div>:<div className="data-empty"><b>Обращений не найдено</b></div>}</section>:
      <section className="pipeline-board">{pipelineStages.slice().sort((a,b)=>a.position-b.position).map(stage=>{const items=opportunities.filter(item=>stage.id==="no-stage"?!item.stageId:item.stageId===stage.id);return <div className="pipeline-column" key={stage.id}><header><b>{stage.name}</b><span>{items.length}</span></header><div>{items.map(item=><article key={item.id}><h3>{item.title}</h3><p>{item.patientName||"Пациент"}</p><footer><b>{item.expectedAmountMinor?money(item.expectedAmountMinor,item.currency):"Сумма не указана"}</b><time>{formatDate(item.createdAt)}</time></footer></article>)}{items.length===0&&<div className="column-empty">Пусто</div>}</div></div>})}</section>}
    {showCreate&&<div className="modal-backdrop" onMouseDown={()=>setShowCreate(false)}><form className="patient-form-modal" onSubmit={create} onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">CRM</span><h2>Новое обращение</h2></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><div className="patient-form-grid"><label>Имя<input name="firstName" required autoFocus/></label><label>Фамилия <small>необязательно</small><input name="lastName"/></label><label>Телефон<input name="phone" type="tel" required/></label><label>Email <small>необязательно</small><input name="email" type="email"/></label><label>Организация<select name="organizationId" required defaultValue=""><option value="" disabled>Выберите</option>{organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Филиал <small>необязательно</small><select name="branchId" defaultValue=""><option value="">Не выбран</option>{branches.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Источник <small>необязательно</small><select name="sourceId" defaultValue=""><option value="">Не выбран</option>{sources.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Канал <small>необязательно</small><select name="channelId" defaultValue=""><option value="">Не выбран</option>{channels.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="wide">Интерес <small>необязательно</small><input name="interest" placeholder="Консультация, имплантация…"/></label><label className="wide">Заметки <small>необязательно</small><textarea name="notes" rows={3}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setShowCreate(false)}>Отмена</button><button className="primary" disabled={saving}>{saving?"Сохраняем…":"Создать обращение"}</button></div></form></div>}
  </main>}

function Metric({value,label,money:asMoney=false}:{value:number;label:string;money?:boolean}){return <div><b>{asMoney?new Intl.NumberFormat("ru-RU").format(value/100):value}</b><span>{label}</span></div>}
function value(form:FormData,name:string){return String(form.get(name)||"").trim()||undefined}
function leadStatus(value:Lead["status"]){return ({new:"Новый",qualified:"Квалифицирован",converted:"Конвертирован",lost:"Потерян"})[value]}
function money(value:number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency,maximumFractionDigits:0}).format(value/100)}
function formatDate(value:string){return new Date(value).toLocaleDateString("ru-RU",{day:"2-digit",month:"short"})}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос"}
