"use client";

import Link from "next/link";
import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { useAuth } from "../auth-shell";

interface Patient{id:string;firstName:string;lastName:string;middleName?:string;birthDate?:string;sex:"female"|"male"|"unknown";phone:string;email?:string;notes?:string;createdAt:string}
interface Appointment{patientId?:string;startsAt:string;doctorName:string;status:string}
interface Balance{balances:{currency:string;balanceMinor:number}[]}
type Column="iin"|"phone"|"last"|"next"|"doctor"|"balance"|"status";type Sort="name"|"created"|"visit";
const PAGE_SIZE=12;

export default function PatientsPage(){const {session,request}=useAuth();const [patients,setPatients]=useState<Patient[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[balances,setBalances]=useState<Record<string,string>>({});
  const [query,setQuery]=useState(""),[appliedQuery,setAppliedQuery]=useState(""),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[showCreate,setShowCreate]=useState(false),[notice,setNotice]=useState("");
  const [sort,setSort]=useState<Sort>("name"),[page,setPage]=useState(1),[showColumns,setShowColumns]=useState(false),[onlyWithVisits,setOnlyWithVisits]=useState(false);
  const [columns,setColumns]=useState<Record<Column,boolean>>({iin:true,phone:true,last:true,next:true,doctor:true,balance:true,status:true});const canCreate=session.permissions.includes("patients.create");
  const load=useCallback(async()=>{setLoading(true);try{const now=new Date(),from=new Date(now),to=new Date(now);from.setDate(from.getDate()-31);to.setDate(to.getDate()+31);const [p,a]=await Promise.all([request<Patient[]>(`/patients${appliedQuery?`?q=${encodeURIComponent(appliedQuery)}`:""}`),request<Appointment[]>(`/appointments?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`).catch(()=>[])]);setPatients(p);setAppointments(a);setNotice("");}catch(error){setNotice(message(error));}finally{setLoading(false);}},[appliedQuery,request]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{setPage(1);},[appliedQuery,onlyWithVisits,sort]);
  const visitMap=useMemo(()=>{const result:Record<string,{last?:Appointment;next?:Appointment}>={};const now=Date.now();for(const item of appointments){if(!item.patientId)continue;const current=result[item.patientId]??{};const at=new Date(item.startsAt).getTime();if(at<now&&(!current.last||new Date(current.last.startsAt).getTime()<at))current.last=item;if(at>=now&&(!current.next||new Date(current.next.startsAt).getTime()>at))current.next=item;result[item.patientId]=current;}return result;},[appointments]);
  const sorted=useMemo(()=>patients.filter(patient=>!onlyWithVisits||visitMap[patient.id]?.next).slice().sort((a,b)=>sort==="name"?`${a.lastName}${a.firstName}`.localeCompare(`${b.lastName}${b.firstName}`,"ru"):sort==="created"?new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime():(new Date(visitMap[a.id]?.next?.startsAt??"9999").getTime()-new Date(visitMap[b.id]?.next?.startsAt??"9999").getTime())),[onlyWithVisits,patients,sort,visitMap]);
  const pageCount=Math.max(1,Math.ceil(sorted.length/PAGE_SIZE)),pageItems=sorted.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  useEffect(()=>{if(!session.permissions.includes("finance.read"))return;const missing=pageItems.filter(item=>balances[item.id]===undefined);if(!missing.length)return;void Promise.all(missing.map(async patient=>{try{const balance=await request<Balance>(`/patients/${patient.id}/balance`);return [patient.id,balance.balances.length?balance.balances.map(item=>money(item.balanceMinor,item.currency)).join(" · "):"0 ₸"] as const;}catch{return [patient.id,"—"] as const;}})).then(values=>setBalances(current=>({...current,...Object.fromEntries(values)})));},[balances,pageItems,request,session.permissions]);
  function search(event:FormEvent){event.preventDefault();setAppliedQuery(query.trim());}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget,form=new FormData(element);setCreating(true);const optional=(name:string)=>String(form.get(name)??"").trim()||undefined;try{await request("/patients",{method:"POST",body:JSON.stringify({lastName:String(form.get("lastName")),firstName:String(form.get("firstName")),middleName:optional("middleName"),birthDate:optional("birthDate"),sex:String(form.get("sex")),phone:String(form.get("phone")),email:optional("email"),notes:optional("notes")})});element.reset();setShowCreate(false);await load();setNotice("Пациент добавлен");}catch(error){setNotice(message(error));}finally{setCreating(false);}}
  const gridTemplate=["minmax(220px,1.5fr)",columns.iin&&"120px",columns.phone&&"150px",columns.last&&"130px",columns.next&&"145px",columns.doctor&&"minmax(140px,1fr)",columns.balance&&"105px",columns.status&&"100px","42px"].filter(Boolean).join(" ");
  return <main className="patients-page"><header className="registry-header"><div><span className="page-kicker">Клиническая база</span><h1>Пациенты</h1><p>{patients.length} записей в реестре</p></div>{canCreate&&<button className="primary" onClick={()=>setShowCreate(true)}>＋ Новый пациент</button>}</header>
    {notice&&<div className="toast-notice"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
    <section className="registry-panel"><div className="registry-toolbar"><form onSubmit={search} className="registry-search"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ФИО, ИИН или телефон"/><kbd>Enter</kbd></form><button className={onlyWithVisits?"filter-button active":"filter-button"} onClick={()=>setOnlyWithVisits(value=>!value)}>≡ С записью {onlyWithVisits&&<i/>}</button><select value={sort} onChange={event=>setSort(event.target.value as Sort)} aria-label="Сортировка"><option value="name">По имени</option><option value="visit">По ближайшему визиту</option><option value="created">Сначала новые</option></select><div className="column-picker"><button onClick={()=>setShowColumns(value=>!value)}>▥ Столбцы</button>{showColumns&&<div>{(Object.keys(columns) as Column[]).map(key=><label key={key}><input type="checkbox" checked={columns[key]} onChange={()=>setColumns(value=>({...value,[key]:!value[key]}))}/>{columnLabel(key)}</label>)}</div>}</div></div>
      {loading?<div className="data-empty">Загружаем пациентов…</div>:pageItems.length===0?<div className="data-empty"><b>{appliedQuery?"Ничего не найдено":"Пациентов пока нет"}</b><span>{appliedQuery?"Проверьте запрос или очистите поиск.":"Добавьте первую карточку пациента."}</span></div>:<div className="registry-table" style={{"--patient-grid":gridTemplate} as React.CSSProperties}><div className="registry-head"><span>Пациент</span>{columns.iin&&<span>ИИН</span>}{columns.phone&&<span>Телефон</span>}{columns.last&&<span>Последний визит</span>}{columns.next&&<span>Следующий визит</span>}{columns.doctor&&<span>Врач</span>}{columns.balance&&<span>Баланс</span>}{columns.status&&<span>Статус</span>}<span/></div>{pageItems.map(patient=>{const visits=visitMap[patient.id];return <Link className="registry-row" style={{gridTemplateColumns:gridTemplate}} href={`/patients/${patient.id}`} key={patient.id}><span className="patient-person"><i>{initials(patient)}</i><span><b>{patient.lastName} {patient.firstName} {patient.middleName??""}</b><small>{patient.email||sexLabel(patient.sex)}</small></span></span>{columns.iin&&<span className="muted-cell">—</span>}{columns.phone&&<span>{patient.phone}</span>}{columns.last&&<span>{visits?.last?formatVisit(visits.last.startsAt):"—"}</span>}{columns.next&&<span className={visits?.next?"next-visit":"muted-cell"}>{visits?.next?formatVisit(visits.next.startsAt):"Не записан"}</span>}{columns.doctor&&<span>{visits?.next?.doctorName||visits?.last?.doctorName||"—"}</span>}{columns.balance&&<span className="balance-cell">{balances[patient.id]??"…"}</span>}{columns.status&&<span><i className="patient-status-dot"/>Активен</span>}<button className="row-menu" onClick={event=>event.preventDefault()} aria-label="Действия">•••</button></Link>})}</div>}
      <footer className="registry-pagination"><span>Показано {(page-1)*PAGE_SIZE+1}–{Math.min(page*PAGE_SIZE,sorted.length)} из {sorted.length}</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>‹</button>{Array.from({length:Math.min(pageCount,5)},(_,index)=>{const value=index+1;return <button className={page===value?"active":""} key={value} onClick={()=>setPage(value)}>{value}</button>})}<button disabled={page===pageCount} onClick={()=>setPage(value=>value+1)}>›</button></div></footer></section>
    {showCreate&&<div className="modal-backdrop" onMouseDown={()=>setShowCreate(false)}><form className="patient-form-modal" onSubmit={create} onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="page-kicker">Новая карточка</span><h2>Добавить пациента</h2></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><div className="patient-form-grid"><Field name="lastName" label="Фамилия"/><Field name="firstName" label="Имя"/><Field name="middleName" label="Отчество" optional/><Field name="birthDate" label="Дата рождения" type="date" optional/><label>Пол<select name="sex" defaultValue="unknown"><option value="unknown">Не указан</option><option value="female">Женский</option><option value="male">Мужской</option></select></label><Field name="phone" label="Телефон" type="tel"/><Field name="email" label="Email" type="email" optional/><label className="wide">Заметки <small>необязательно</small><textarea name="notes" rows={4}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setShowCreate(false)}>Отмена</button><button className="primary" disabled={creating}>{creating?"Создаём…":"Создать пациента"}</button></div></form></div>}
  </main>;
}
function Field({name,label,type="text",optional=false}:{name:string;label:string;type?:string;optional?:boolean}){return <label>{label}{optional&&<small>необязательно</small>}<input name={name} type={type} required={!optional}/></label>}
function columnLabel(key:Column){return({iin:"ИИН",phone:"Телефон",last:"Последний визит",next:"Следующий визит",doctor:"Врач",balance:"Баланс",status:"Статус"})[key]}
function initials(patient:Patient){return `${patient.lastName[0]??""}${patient.firstName[0]??""}`.toUpperCase()}
function sexLabel(value:Patient["sex"]){return value==="female"?"Женщина":value==="male"?"Мужчина":"Пол не указан"}
function formatVisit(value:string){return new Date(value).toLocaleDateString("ru-RU",{day:"2-digit",month:"short",year:"2-digit"})}
function money(value:number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency,maximumFractionDigits:0}).format(value/100)}
function message(error:unknown){return error instanceof Error?error.message:"Не удалось выполнить запрос"}
